// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from "./.slc-verify/verify.js";
import * as fsm from "./captain.fsm.js";

const PINNED = {
  "initial": "hub",
  "captain": [
    {
      "state": "deciding",
      "actor": "captain",
      "sourceItem": "CAPTAIN-1",
      "player": "",
      "resultKeys": [
        "deliver",
        "dismiss",
        "respond",
        "runtime",
        "start",
        "switch"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "hub",
          "guarded": true
        },
        {
          "index": 1,
          "target": "hub",
          "guarded": true
        },
        {
          "index": 2,
          "target": "reporting",
          "guarded": true
        },
        {
          "index": 3,
          "target": "reporting",
          "guarded": true
        },
        {
          "index": 4,
          "target": "reporting",
          "guarded": true
        },
        {
          "index": 5,
          "target": "reporting",
          "guarded": true
        },
        {
          "index": 6,
          "target": "reporting",
          "guarded": true
        },
        {
          "index": 7,
          "target": "failed",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "hub",
          "guarded": true
        },
        {
          "index": 1,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    },
    {
      "state": "answeringCommand",
      "actor": "captain",
      "sourceItem": "CAPTAIN-2",
      "player": "",
      "resultKeys": [
        "done"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "hub",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    },
    {
      "state": "reporting",
      "actor": "captain",
      "sourceItem": "CAPTAIN-3",
      "player": "",
      "resultKeys": [
        "done"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "hub",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    }
  ],
  "quiescent": [
    {
      "state": "hub",
      "final": false,
      "on": {
        "BOSS_TURN": [
          {
            "index": 0,
            "target": "deciding",
            "guarded": true
          }
        ],
        "PARSED_RESPOND": [
          {
            "index": 0,
            "target": "answeringCommand",
            "guarded": true
          }
        ],
        "PARSED_ACTION": [
          {
            "index": 0,
            "target": "deciding",
            "guarded": true
          }
        ],
        "SHUTDOWN": [
          {
            "index": 0,
            "target": "shutdown",
            "guarded": false
          }
        ]
      }
    },
    {
      "state": "failed",
      "final": false,
      "on": {
        "BOSS_TURN": [
          {
            "index": 0,
            "target": "deciding",
            "guarded": true
          }
        ],
        "PARSED_RESPOND": [
          {
            "index": 0,
            "target": "answeringCommand",
            "guarded": true
          }
        ],
        "PARSED_ACTION": [
          {
            "index": 0,
            "target": "deciding",
            "guarded": true
          }
        ],
        "SHUTDOWN": [
          {
            "index": 0,
            "target": "shutdown",
            "guarded": false
          }
        ]
      }
    },
    {
      "state": "shutdown",
      "final": true,
      "on": {}
    }
  ],
  "rootOn": {},
  "interruptTargets": []
};

describe("captain: FSM introspection", () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
