// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./captain.fsm.ts
// Player bind:   none (the session Captain declares no player behavior)
// Boss event:    deterministic controller entry (slc/link.md §Boss-event
//                mapping): every turn maps from the exact Boss text and the
//                host's command-parse resolution supplied through the linked
//                options' controller port — BOSS_TURN / PARSED_RESPOND /
//                PARSED_ACTION / SHUTDOWN — with no classifier judge call.
// Captain calls: hidden controller form (slc/link.md §Captain adjudication,
//                DR-029): decision and closing-reply calls run
//                `{ visibility: 'hidden' }`; the host's session-Captain
//                wrapper owns the durable-conversation resume selection and
//                pins the returned token (the runtime requests
//                `resume: false` as the typed placeholder and its traces
//                carry no resume member). The decision reply is `{ action,
//                … }` control JSON validated here against the declared
//                decision-state contract — never adjudicated through a
//                judge call and never Boss presentation; controller prose
//                reaches Boss only as host-validated captain speech through
//                the host's presentation seam (cligent
//                `CaptainContext.emitReply`).
// Contract:      types imported and re-exported from
//                @sublang/playbook/runtime (slc/link.md §Output); the
//                shared createXStatePlaybookRuntime factory from
//                @sublang/playbook/xstate-runtime interprets the FSM
//                (DR-019). This module carries only the Captain-specific
//                spec: options validation (catalog + controller port),
//                deterministic entry mapping, the controller captain-call
//                strategy with its single corrective re-ask (CAPPLAY-18),
//                controller-port submission, and status formatting.
// Compat:        spec.compat = { artifactSchema: 3, runtimeAbi: 1 }
//                (DR-022; checked at construction by the loading engine).

import {
  createXStatePlaybookRuntime,
  defaultComposeCaptainPrompt,
  emptyPlaybookEffectLedger,
  normalizeError,
  normalizeErrorCompact,
  parseJudgeJson,
  snapshotJsonValue,
  type PlaybookActorOutput,
  type PlaybookCaptainInput,
  type ScheduledStatus,
  type XStateCaptainStrategyRun,
  type XStatePlaybookRuntimeSpecV3,
  type XStateRepositoryCapability,
} from '../../../src/xstate-runtime.js';
import {
  captainMachine,
  type CaptainInput,
  type CaptainOutput,
  type DecisionAction,
  type EnabledPlaybook,
  type ParsedActingDecision,
  type SettlementEvidence,
  type SettlementReceiptEvidence,
  type SettlementUnresolvedEffectEvidence,
} from './captain.fsm.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlaybookPorts,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlayerResult,
} from '@sublang/playbook/runtime';

// Public contract re-exports (slc/link.md §Output): every linked playbook
// shares the one contract definition from @sublang/playbook/runtime.
export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlayerResult,
  PlaybookPorts,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
};

// Artifact-declared controller types (slc/link.md §PlaybookRuntime contract:
// host-supplied port-shaped callbacks are linker-exposed option members whose
// types the artifact itself declares, so `PlaybookPorts` stays six members).
export type {
  DecisionAction,
  EnabledPlaybook,
  ParsedActingDecision,
  SettlementEvidence,
  SettlementReceiptEvidence,
};

/** One nonempty complete standalone request selected for `start` or `switch`. */
export type CaptainControllerInput = string;

/** One validated controller selection submitted through the port (DR-029, DR-038). */
export type CaptainControllerSelection =
  | { readonly action: 'respond'; readonly text: string }
  | { readonly action: 'resume'; readonly playbookId: string }
  | {
      readonly action: 'start' | 'switch';
      readonly playbookId: string;
      /** Complete standalone request synthesized from the remembered Boss conversation. */
      readonly input: CaptainControllerInput;
    }
  | { readonly action: 'dismiss' }
  | { readonly action: 'deliver' }
  | { readonly action: 'runtime'; readonly actionId: string };

/**
 * The host's deterministic per-turn resolution (CAPTAIN-7 parse table):
 * `undefined` sends the turn to the hidden decision call; `respond` routes
 * the dedicated prose item; `action` injects the parse-resolved decision
 * object; `shutdown` is the host teardown entry to the machine's one final
 * state.
 */
export type CaptainParsedResolution =
  | { readonly kind: 'respond' }
  | { readonly kind: 'action'; readonly decision: ParsedActingDecision }
  | { readonly kind: 'shutdown' };

/**
 * The host-supplied controller port (CAPPLAY-9, DR-029): one validated
 * selection per Boss turn in, its settlement back as the only evidence of
 * effects. The optional `resolveParsedTurn` member supplies the host's
 * deterministic command-parse resolution for the entry mapping.
 */
export interface CaptainControllerPort {
  submit(
    selection: CaptainControllerSelection,
    signal: AbortSignal,
  ): Promise<SettlementEvidence>;
  resolveParsedTurn?(text: string): CaptainParsedResolution | undefined;
}

export interface PlaybookRuntimeOptions {
  readonly enabledPlaybooks: readonly EnabledPlaybook[];
  /**
   * The host-supplied controller port. Every Boss turn settles through it
   * (CAPPLAY-9), so it is declared required. It was optional here only until
   * the IR-036 task-4 shell rework landed; that rework has landed and the
   * shell now supplies the port on every construction, so a declaration that
   * still admitted its absence typechecked a runtime that cannot settle a
   * single turn.
   */
  readonly controller: CaptainControllerPort;
}

/**
 * The validated option record the engine carries. It differs from the public
 * declaration in exactly one place: `controller` is optional here, because a
 * construction from untyped JavaScript can still omit it and the shape has to
 * describe what validation actually accepts. Where that ends is
 * `requireControllerPort` — the first Boss turn, with a named error rather
 * than a silent one.
 */
type ValidatedCaptainOptions = Omit<PlaybookRuntimeOptions, 'controller'> & {
  readonly controller?: CaptainControllerPort;
};

function assertNonEmptyString(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new TypeError(`${label} must be a non-empty string`);
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function validateEnabledPlaybooks(
  value: unknown,
): readonly EnabledPlaybook[] {
  if (!Array.isArray(value)) {
    throw new TypeError('enabledPlaybooks must be an array');
  }
  const ids = new Set<string>();
  return Object.freeze(
    value.map((entry: unknown, index) => {
      if (!isRecord(entry)) {
        throw new TypeError(`enabledPlaybooks[${index}] must be an object`);
      }
      const keys = Object.keys(entry).sort();
      if (keys.join('\0') !== ['command', 'id', 'intent'].join('\0')) {
        throw new TypeError(
          `enabledPlaybooks[${index}] must contain exactly id, command, and intent`,
        );
      }
      const id = assertNonEmptyString(entry.id, `enabledPlaybooks[${index}].id`);
      const command = assertNonEmptyString(
        entry.command,
        `enabledPlaybooks[${index}].command`,
      );
      const intent = assertNonEmptyString(
        entry.intent,
        `enabledPlaybooks[${index}].intent`,
      );
      if (ids.has(id)) {
        throw new TypeError(`enabledPlaybooks id ${id} is duplicated`);
      }
      ids.add(id);
      return Object.freeze({ id, command, intent });
    }),
  );
}

function validateControllerPort(value: unknown): CaptainControllerPort {
  if (value === null || typeof value !== 'object') {
    throw new TypeError('options.controller must be an object');
  }
  const record = value as Record<string, unknown>;
  if (typeof record.submit !== 'function') {
    throw new TypeError('options.controller.submit must be a function');
  }
  if (
    record.resolveParsedTurn !== undefined &&
    typeof record.resolveParsedTurn !== 'function'
  ) {
    throw new TypeError(
      'options.controller.resolveParsedTurn must be a function when present',
    );
  }
  return value as CaptainControllerPort;
}

function snapshotCaptainOptions(value: unknown): ValidatedCaptainOptions {
  if (!isRecord(value)) {
    throw new TypeError('Captain runtime options must be an object');
  }
  const allowed = new Set(['enabledPlaybooks', 'controller']);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw new TypeError(`Captain runtime options.${key} is not declared`);
    }
  }
  const enabledPlaybooks = validateEnabledPlaybooks(value.enabledPlaybooks);
  const controller =
    value.controller === undefined
      ? undefined
      : validateControllerPort(value.controller);
  return Object.freeze({
    enabledPlaybooks,
    ...(controller === undefined ? {} : { controller }),
  });
}

// ---------------------------------------------------------------------------
// Deterministic controller entry mapping (slc/link.md §Boss-event mapping):
// the exact Boss text rides the runtime-owned `bossText` field; the host's
// parse resolution selects the hub entry arm; no classifier judge call runs.
// ---------------------------------------------------------------------------

function validateParsedActingDecision(value: unknown): ParsedActingDecision {
  if (!isRecord(value)) {
    throw new TypeError('parse-resolved decision must be an object');
  }
  if (value.action === 'deliver') {
    if (Object.keys(value).length !== 1) {
      throw new TypeError('a parse-resolved deliver decision carries no payload');
    }
    return { action: 'deliver' };
  }
  if (value.action === 'resume') {
    const allowed = new Set(['action', 'playbookId']);
    for (const key of Object.keys(value)) {
      if (!allowed.has(key)) {
        throw new TypeError(`parse-resolved decision carries undeclared ${key}`);
      }
    }
    return {
      action: 'resume',
      playbookId: assertNonEmptyString(
        value.playbookId,
        'parse-resolved decision playbookId',
      ),
    };
  }
  if (value.action !== 'start' && value.action !== 'switch') {
    throw new TypeError(
      `parse-resolved decision names unknown action ${String(value.action)}`,
    );
  }
  const allowed = new Set(['action', 'playbookId', 'input']);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw new TypeError(`parse-resolved decision carries undeclared ${key}`);
    }
  }
  return {
    action: value.action,
    playbookId: assertNonEmptyString(
      value.playbookId,
      'parse-resolved decision playbookId',
    ),
    input: assertNonEmptyString(value.input, 'parse-resolved decision input'),
  };
}

function classifyControllerTurn(
  text: string,
  _ports: PlaybookPorts,
  _signal: AbortSignal,
  _snapshotOrState: unknown,
  _boundary?: unknown,
  options?: ValidatedCaptainOptions,
): Promise<Record<string, unknown> | undefined> {
  const resolution = options?.controller?.resolveParsedTurn?.(text);
  if (resolution === undefined) {
    return Promise.resolve({ type: 'BOSS_TURN', bossText: text });
  }
  if (!isRecord(resolution)) {
    throw new TypeError('controller parse resolution must be an object');
  }
  const widened = resolution as {
    readonly kind?: unknown;
    readonly decision?: unknown;
  };
  switch (widened.kind) {
    case 'respond':
      return Promise.resolve({ type: 'PARSED_RESPOND', bossText: text });
    case 'action':
      return Promise.resolve({
        type: 'PARSED_ACTION',
        bossText: text,
        decision: validateParsedActingDecision(widened.decision),
      });
    case 'shutdown':
      return Promise.resolve({ type: 'SHUTDOWN' });
    default:
      throw new TypeError(
        `controller parse resolution names unknown kind ${String(widened.kind)}`,
      );
  }
}

// ---------------------------------------------------------------------------
// Decision-reply validation (CAPPLAY-18): the hidden decision call's reply is
// `{ action, … }` control JSON over the closed set, validated against the
// declared decision-state contract — known action, required payload fields,
// catalog membership, never this Captain playbook itself as a target. A
// malformed reply earns exactly one corrective call appending the rejection
// reason and the restated reply contract; a second malformed reply settles
// the turn as a recoverable hub return with no action executed.
// ---------------------------------------------------------------------------

const RESTATED_REPLY_CONTRACT = [
  'Reply again with exactly one JSON object `{ "action": …, … }` and no other text, selecting exactly one action from the closed set `respond` | `resume` | `start` | `switch` | `dismiss` | `deliver` | `runtime`:',
  '`{ "action": "respond", "text": … }`, `{ "action": "resume", "playbookId": … }`, `{ "action": "start", "playbookId": …, "input": … }`, `{ "action": "switch", "playbookId": …, "input": … }`, `{ "action": "dismiss" }`, `{ "action": "deliver" }`, or `{ "action": "runtime", "actionId": … }`; every `input` is one nonempty complete standalone request.',
].join('\n');

function correctiveDecisionPrompt(prompt: string, reason: string): string {
  return [
    prompt,
    '',
    `Your previous control reply was rejected: ${reason}.`,
    RESTATED_REPLY_CONTRACT,
  ].join('\n');
}

type DecisionReplyReading =
  | { readonly selection: CaptainControllerSelection; readonly reason?: undefined }
  | { readonly selection?: undefined; readonly reason: string };

function readDecisionReply(
  reply: string,
  options: ValidatedCaptainOptions,
  selfPlaybookId: string,
  declaredActions: ReadonlySet<string>,
): DecisionReplyReading {
  let parsed: unknown;
  try {
    parsed = parseJudgeJson(reply);
  } catch {
    return { reason: 'the reply contains no recoverable JSON object' };
  }
  if (!isRecord(parsed)) {
    return { reason: 'the reply is not a JSON object' };
  }
  const action = parsed.action;
  if (typeof action !== 'string' || !declaredActions.has(action)) {
    return {
      reason: `the reply names no known action (got ${JSON.stringify(action ?? null)})`,
    };
  }
  const requireKeys = (
    required: readonly string[],
    tolerated: readonly string[] = [],
  ): string | undefined => {
    for (const key of required) {
      if (!(key in parsed)) {
        return `the ${action} selection omits required field \`${key}\``;
      }
    }
    for (const key of Object.keys(parsed)) {
      if (
        key !== 'action' &&
        !required.includes(key) &&
        !tolerated.includes(key)
      ) {
        return `the ${action} selection carries undeclared field \`${key}\``;
      }
    }
    return undefined;
  };
  const nonEmpty = (key: string): string | undefined =>
    typeof parsed[key] === 'string' && parsed[key].trim().length > 0
      ? undefined
      : `the ${action} selection's \`${key}\` must be a non-empty string`;
  switch (action) {
    case 'respond': {
      const shape = requireKeys(['text']) ?? nonEmpty('text');
      if (shape !== undefined) return { reason: shape };
      return { selection: { action, text: parsed.text as string } };
    }
    case 'resume': {
      const shape = requireKeys(['playbookId']) ?? nonEmpty('playbookId');
      if (shape !== undefined) return { reason: shape };
      const playbookId = parsed.playbookId as string;
      if (playbookId === selfPlaybookId) {
        return {
          reason: `the ${action} target may never be this Captain playbook itself`,
        };
      }
      if (
        !options.enabledPlaybooks.some((entry) => entry.id === playbookId)
      ) {
        return {
          reason: `the ${action} target ${JSON.stringify(playbookId)} is not an enabled catalog id`,
        };
      }
      return { selection: { action, playbookId } };
    }
    case 'start':
    case 'switch': {
      const shape =
        requireKeys(['playbookId', 'input']) ??
        nonEmpty('playbookId') ??
        nonEmpty('input');
      if (shape !== undefined) return { reason: shape };
      const playbookId = parsed.playbookId as string;
      if (playbookId === selfPlaybookId) {
        return {
          reason: `the ${action} target may never be this Captain playbook itself`,
        };
      }
      if (
        !options.enabledPlaybooks.some((entry) => entry.id === playbookId)
      ) {
        return {
          reason: `the ${action} target ${JSON.stringify(playbookId)} is not an enabled catalog id`,
        };
      }
      return {
        selection: {
          action,
          playbookId,
          input: parsed.input as string,
        },
      };
    }
    case 'dismiss': {
      const shape = requireKeys([]);
      if (shape !== undefined) return { reason: shape };
      return { selection: { action } };
    }
    case 'deliver': {
      // A deliver selection carries no text payload: the host is
      // authoritative for the delivered text, so a carried `text` is
      // ignored and never delivered (CAPPLAY-9).
      const shape = requireKeys([], ['text']);
      if (shape !== undefined) return { reason: shape };
      return { selection: { action } };
    }
    case 'runtime': {
      const shape = requireKeys(['actionId']) ?? nonEmpty('actionId');
      if (shape !== undefined) return { reason: shape };
      return { selection: { action, actionId: parsed.actionId as string } };
    }
    default:
      return { reason: `the reply names no known action (${action})` };
  }
}

function selectionFromParsedDecision(
  decision: ParsedActingDecision,
): CaptainControllerSelection {
  if (decision.action === 'deliver') {
    return { action: 'deliver' };
  }
  if (decision.action === 'resume') {
    return { action: 'resume', playbookId: decision.playbookId };
  }
  // A parse-resolved `start` / `switch` is always the exact command remainder
  // supplied by the host (CAPTAIN-7 command table).
  return {
    action: decision.action,
    playbookId: decision.playbookId,
    input: decision.input,
  };
}

/** The machine retains the selected standalone input and settlement evidence. */
function decisionOutputOf(
  selection: CaptainControllerSelection,
): Record<string, unknown> {
  if (selection.action === 'start' || selection.action === 'switch') {
    return {
      guard: selection.action,
      playbookId: selection.playbookId,
      input: selection.input,
    };
  }
  return { ...selection, guard: selection.action };
}

// ---------------------------------------------------------------------------
// Settlement validation: the returned settlement is the only evidence of
// effects, and the machine retains only its status, facts, bounded unresolved
// effects, receipt disposition, and leaf-state summary (CAPPLAY-10). A
// malformed settlement is a host control-plane failure.
// ---------------------------------------------------------------------------

const SETTLEMENT_GIT_OID_PATTERN = /^[0-9a-f]{40}(?:[0-9a-f]{24})?$/;
const SETTLEMENT_UNRESOLVED_CLASSIFICATIONS = new Set<
  SettlementUnresolvedEffectEvidence['classification']
>([
  'one-descendant-commit',
  'multiple-commits',
  'rewritten-or-non-descendant',
  'worktree-only-change',
  'concurrent-or-foreign-change',
  'observation-ambiguous',
  'incomplete',
]);

function validateSettlementUnresolvedEffects(
  value: unknown,
): readonly SettlementUnresolvedEffectEvidence[] {
  const detached = snapshotJsonValue(
    value,
    'controller settlement unresolvedEffects',
  );
  if (!Array.isArray(detached)) {
    throw new TypeError(
      'controller settlement unresolvedEffects must be an array',
    );
  }
  for (const [index, raw] of detached.entries()) {
    const path = `controller settlement unresolvedEffects[${index}]`;
    if (!isRecord(raw)) {
      throw new TypeError(`${path} must be an object`);
    }
    const allowed = new Set([
      'classification',
      'baselineHead',
      'afterHead',
      'commitOid',
    ]);
    const unknown = Object.keys(raw).find((key) => !allowed.has(key));
    if (unknown !== undefined) {
      throw new TypeError(`${path} carries undeclared ${unknown}`);
    }
    if (
      typeof raw.classification !== 'string' ||
      !SETTLEMENT_UNRESOLVED_CLASSIFICATIONS.has(
        raw.classification as SettlementUnresolvedEffectEvidence['classification'],
      )
    ) {
      throw new TypeError(`${path} classification is not supported`);
    }
    if (
      typeof raw.baselineHead !== 'string' ||
      !SETTLEMENT_GIT_OID_PATTERN.test(raw.baselineHead)
    ) {
      throw new TypeError(`${path} baselineHead must be a Git OID`);
    }
    if (
      'afterHead' in raw &&
      (typeof raw.afterHead !== 'string' ||
        !SETTLEMENT_GIT_OID_PATTERN.test(raw.afterHead))
    ) {
      throw new TypeError(`${path} afterHead must be a Git OID`);
    }
    if (
      raw.classification !== 'observation-ambiguous' &&
      raw.classification !== 'incomplete' &&
      !('afterHead' in raw)
    ) {
      throw new TypeError(
        `${path} afterHead is required for ${raw.classification}`,
      );
    }
    if (raw.classification === 'one-descendant-commit') {
      if (
        typeof raw.commitOid !== 'string' ||
        !SETTLEMENT_GIT_OID_PATTERN.test(raw.commitOid) ||
        raw.commitOid !== raw.afterHead
      ) {
        throw new TypeError(
          `${path} commitOid must equal afterHead for one-descendant-commit`,
        );
      }
    } else if ('commitOid' in raw) {
      throw new TypeError(
        `${path} commitOid is permitted only for one-descendant-commit`,
      );
    }
  }
  return detached as unknown as readonly SettlementUnresolvedEffectEvidence[];
}

function validateSettlement(value: unknown): SettlementEvidence {
  if (!isRecord(value)) {
    throw new TypeError('controller settlement must be an object');
  }
  const allowed = new Set([
    'status',
    'facts',
    'unresolvedEffects',
    'reason',
    'receipt',
    'leafStateSummary',
  ]);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw new TypeError(`controller settlement carries undeclared ${key}`);
    }
  }
  if (
    value.status !== 'ok' &&
    value.status !== 'rejected' &&
    value.status !== 'failed'
  ) {
    throw new TypeError(
      `controller settlement status must be ok | rejected | failed (got ${String(value.status)})`,
    );
  }
  if (
    !Array.isArray(value.facts) ||
    value.facts.some((fact: unknown) => typeof fact !== 'string')
  ) {
    throw new TypeError('controller settlement facts must be a string array');
  }
  if (!Object.prototype.hasOwnProperty.call(value, 'unresolvedEffects')) {
    throw new TypeError('controller settlement unresolvedEffects is required');
  }
  const unresolvedEffects = validateSettlementUnresolvedEffects(
    value.unresolvedEffects,
  );
  if ('reason' in value && typeof value.reason !== 'string') {
    throw new TypeError('controller settlement reason must be a string');
  }
  if (
    'leafStateSummary' in value &&
    typeof value.leafStateSummary !== 'string'
  ) {
    throw new TypeError(
      'controller settlement leafStateSummary must be a string',
    );
  }
  let receipt: SettlementReceiptEvidence | undefined;
  if ('receipt' in value) {
    if (!isRecord(value.receipt)) {
      throw new TypeError('controller settlement receipt must be an object');
    }
    const receiptAllowed = new Set(['disposition', 'reason', 'error']);
    for (const key of Object.keys(value.receipt)) {
      if (!receiptAllowed.has(key)) {
        throw new TypeError(
          `controller settlement receipt carries undeclared ${key}`,
        );
      }
    }
    const disposition = value.receipt.disposition;
    if (
      disposition !== 'executed' &&
      disposition !== 'rejected' &&
      disposition !== 'failed'
    ) {
      throw new TypeError(
        'controller settlement receipt disposition must be executed | rejected | failed',
      );
    }
    if ('reason' in value.receipt && typeof value.receipt.reason !== 'string') {
      throw new TypeError(
        'controller settlement receipt reason must be a string',
      );
    }
    let error: { name: string; message: string } | undefined;
    if ('error' in value.receipt) {
      const compact = normalizeErrorCompact(value.receipt.error);
      if (compact === undefined) {
        throw new TypeError(
          'controller settlement receipt error must be a normalized error',
        );
      }
      error = compact;
    }
    receipt = Object.freeze({
      disposition,
      ...(typeof value.receipt.reason === 'string'
        ? { reason: value.receipt.reason }
        : {}),
      ...(error === undefined ? {} : { error: Object.freeze(error) }),
    });
  }
  return Object.freeze({
    status: value.status,
    facts: Object.freeze([...(value.facts as readonly string[])]),
    unresolvedEffects,
    ...(typeof value.reason === 'string' ? { reason: value.reason } : {}),
    ...(receipt === undefined ? {} : { receipt }),
    ...(typeof value.leafStateSummary === 'string'
      ? { leafStateSummary: value.leafStateSummary }
      : {}),
  });
}

// ---------------------------------------------------------------------------
// The controller captain-call strategy (slc/link.md §Captain adjudication,
// controller form). The engine composes the prompt, traces every call as its
// own captain.call pair on the shared serialized lane, and owns
// control-plane latching; this strategy owns the hidden calls, the decision
// validation with its one corrective re-ask, and the controller-port
// submission.
// ---------------------------------------------------------------------------

const HIDDEN = { visibility: 'hidden' } as const;

async function callHidden(
  run: XStateCaptainStrategyRun<ValidatedCaptainOptions>,
  prompt: string,
): Promise<CaptainResult> {
  try {
    return await run.callCaptain(prompt, HIDDEN);
  } catch (error) {
    // DR-028: exactly one corrective re-ask of the same composed call on an
    // empty `ok` result; a second such result follows the failure path from
    // the boundary itself.
    if (!run.isEmptyOkRetry(error)) throw error;
    return await run.callCaptain(prompt, HIDDEN);
  }
}

function requireControllerPort(
  options: ValidatedCaptainOptions,
): CaptainControllerPort {
  if (options.controller === undefined) {
    throw new Error(
      'captain.playbook: the host-supplied controller port is required to settle a Boss turn (CAPPLAY-9); construct the runtime with options.controller',
    );
  }
  return options.controller;
}

async function submitSelection(
  run: XStateCaptainStrategyRun<ValidatedCaptainOptions>,
  selection: CaptainControllerSelection,
): Promise<SettlementEvidence> {
  const port = requireControllerPort(run.options);
  const settlement = validateSettlement(
    await port.submit(selection, run.signal),
  );
  run.signal.throwIfAborted();
  return settlement;
}

async function runDecisionState(
  run: XStateCaptainStrategyRun<ValidatedCaptainOptions>,
): Promise<CaptainOutput> {
  const input = run.input as unknown as CaptainInput;
  const declaredActions = new Set(Object.keys(run.input.result));
  let selection: CaptainControllerSelection;
  if (input.parsedDecision !== undefined) {
    // A parse-resolved turn enters with its decision already made: the
    // injected decision object is the turn's decision and no decision call
    // occurs (CAPTAIN-7, CAPPLAY-6). A malformed injection is a host bug —
    // control-plane, not a corrective re-ask.
    selection = selectionFromParsedDecision(
      validateParsedActingDecision(input.parsedDecision),
    );
  } else {
    const first = await callHidden(run, run.prompt);
    const firstReading = readDecisionReply(
      first.finalText ?? '',
      run.options,
      run.session.playbookId,
      declaredActions,
    );
    if (firstReading.selection !== undefined) {
      selection = firstReading.selection;
    } else {
      // CAPPLAY-18: exactly one corrective call appending the rejection
      // reason and the restated reply contract to the same prompt.
      const second = await callHidden(
        run,
        correctiveDecisionPrompt(run.prompt, firstReading.reason),
      );
      const secondReading = readDecisionReply(
        second.finalText ?? '',
        run.options,
        run.session.playbookId,
        declaredActions,
      );
      if (secondReading.selection === undefined) {
        // A second malformed reply settles the turn as a Boss-appropriate
        // failure reply with no action executed and the engagement stack
        // untouched; the machine returns to its hub (CAPPLAY-18/19). The
        // marker property routes the FSM's authored hub-recovery arm.
        const failure = new Error(
          `the decision reply stayed malformed after one corrective re-ask: ${secondReading.reason}`,
        ) as Error & { controllerDecisionFailure?: boolean };
        failure.name = 'ControllerDecisionError';
        failure.controllerDecisionFailure = true;
        throw run.recoverableFailure(failure);
      }
      selection = secondReading.selection;
    }
  }
  const settlement = await submitSelection(run, selection);
  return {
    ...decisionOutputOf(selection),
    settlement,
  } as unknown as CaptainOutput;
}

async function controllerCaptainStrategy(
  run: XStateCaptainStrategyRun<ValidatedCaptainOptions>,
): Promise<PlaybookActorOutput> {
  if (run.input.stateId === 'deciding') {
    return (await runDecisionState(run)) as unknown as PlaybookActorOutput;
  }
  // The prose states (answeringCommand, reporting): one hidden durable call
  // whose validated text the host surfaces as captain speech through its
  // presentation seam; the machine retains no reply prose (CAPPLAY-10) and
  // the state settles with the default single-outcome `done` contract.
  await callHidden(run, run.prompt);
  return { guard: 'done' };
}

// ---------------------------------------------------------------------------
// Captain-pane status lines. The shell suppresses this runtime's human
// status stream while forwarding structured telemetry (CAPPLAY-9); the
// lines stay Boss-appropriate regardless. The parked hub and the shutdown
// state emit no human status (slc/link.md §Session lifecycle).
// ---------------------------------------------------------------------------

function statusesForState(
  state: PlaybookState,
  context: Record<string, unknown>,
): ScheduledStatus[] {
  switch (state.stateId) {
    case 'deciding':
      return [{ message: '⤷ Captain: decide the Boss turn' }];
    case 'answeringCommand':
      return [{ message: '⤷ Captain: answer the command turn' }];
    case 'reporting':
      return [{ message: '⤷ Captain: compose the closing reply' }];
    case 'failed': {
      const lastError = normalizeErrorCompact(context.lastError);
      return [
        {
          message: '◆ failed',
          ...(lastError === undefined
            ? {}
            : { data: snapshotJsonValue({ lastError }, 'failed status data') }),
        },
      ];
    }
    default:
      return [];
  }
}

const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set();

// Internal export surface for verification and tests. Not part of the
// stable public API; the leading underscore signals "subject to change."
export const _internal = {
  // No placeholder exists in any compiled Captain prompt: the labeled
  // Boss-message, ControlView digest, and catalog digest blocks are
  // shell-composed inside the hidden-control envelope (CAPTAIN-9), so the
  // shared default composer emits the verbatim GEARS domain body.
  composeCaptainPrompt: (input: CaptainInput): string =>
    defaultComposeCaptainPrompt(input as unknown as PlaybookCaptainInput),
  classifyControllerTurn,
  readDecisionReply,
  correctiveDecisionPrompt,
  validateSettlement,
  validateParsedActingDecision,
  statusesForState,
  normalizeError,
  UNFINISHED_FINAL_STATE_IDS,
};

// The Captain-specific spec handed to the shared runtime factory
// (slc/link.md §Output, DR-019). Generic machinery — actor wiring, boundary
// tracing, lifecycle, abort, the parked-session snapshot, and the DR-029
// describe/apply control surface — lives in @sublang/playbook/xstate-runtime.
const runtimeSpec: XStatePlaybookRuntimeSpecV3<ValidatedCaptainOptions> = {
  label: 'CAPTAIN',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  // DR-040: the roleless session Captain has no delegated-player outcome,
  // but schema 3 still makes that absence explicit rather than inferred.
  outcomeAuthority: { governedPlayerStates: {} },
  snapshotOptions: snapshotCaptainOptions,
  machineInput: (options) => ({ enabledPlaybooks: options.enabledPlaybooks }),
  classifyBossText: (text, ports, signal, snapshotOrState, boundary, options) =>
    classifyControllerTurn(
      text,
      ports,
      signal,
      snapshotOrState,
      boundary,
      options,
    ) as Promise<import('xstate').EventObject | undefined>,
  roleStates: {},
  classificationStatus: () => undefined,
  captainStrategy: controllerCaptainStrategy,
  // CAPPLAY-10 / PBRT-52: the Captain's own ControlView context projection —
  // the settlement evidence the machine retains for its decision and reply
  // phases, and nothing else. `enabledPlaybooks` is the host-supplied
  // catalog (an option value), and `parsedDecision` and `lastError` are
  // control-plane scratch; none of the three is settlement evidence, so none
  // is exported. Declaring the list here is what makes "Captain-visible
  // context" an enumerated set rather than whatever the FSM happens to hold.
  controlContextFields: [
    'bossText',
    'selectedAction',
    'settlementStatus',
    'settlementFacts',
    'settlementReason',
    'receiptDisposition',
    'receiptReason',
    'receiptError',
    'leafStateSummary',
    'settlementUnresolvedEffects',
  ],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  statusesForState,
};

// DR-022's compat check fails fast at factory construction. The Captain is
// statically imported by the shell and both CLI front ends, so constructing
// here at module evaluation would turn a future compat mismatch into an
// uncaught ESM-load error that takes even `--help` down; constructing on
// the first runtime request keeps the failure inside the caught
// host-construction boundary that owes the Boss a setup diagnostic.
const rejectInternalCaptainRepositoryWork = async (): Promise<never> => {
  throw new Error(
    'the roleless session Captain cannot perform repository-governed work',
  );
};
const INTERNAL_CAPTAIN_HOST_CAPABILITIES = Object.freeze({
  // The engine does not consult this member for an explicitly empty governed
  // set. Keeping a fail-closed implementation satisfies the schema-3 factory
  // boundary without granting the internal controller repository authority.
  repository: Object.freeze({
    runExclusive: rejectInternalCaptainRepositoryWork,
    runDeferred: rejectInternalCaptainRepositoryWork,
  } satisfies XStateRepositoryCapability),
  effectLedger: Object.freeze({
    snapshot: emptyPlaybookEffectLedger,
    writeAhead: async (): Promise<never> => {
      throw new Error(
        'the roleless session Captain cannot write an effect ledger',
      );
    },
  }),
});

function buildCaptainPlaybookRuntimeFactory() {
  return createXStatePlaybookRuntime(captainMachine, runtimeSpec);
}

let createCaptainPlaybookRuntime:
  | ReturnType<typeof buildCaptainPlaybookRuntimeFactory>
  | undefined;

export function createPlaybookRuntime(
  options: PlaybookRuntimeOptions,
): PlaybookRuntime {
  createCaptainPlaybookRuntime ??= buildCaptainPlaybookRuntimeFactory();
  return createCaptainPlaybookRuntime({
    configuredOptions: options,
    hostCapabilities: INTERNAL_CAPTAIN_HOST_CAPABILITIES,
  });
}

const factory: PlaybookRuntimeFactory<PlaybookRuntimeOptions> =
  createPlaybookRuntime;

export default factory;
