// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test. No compiled Captain
// prompt of the controller machine carries a placeholder: the labeled
// Boss-message, ControlView digest, and catalog digest blocks are
// shell-composed inside the hidden-control envelope (CAPTAIN-9), so the
// composed prompt is the verbatim GEARS domain body.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from "./.slc-verify/verify.js";
import * as fsm from "./captain.fsm.js";
import * as playbook from "./captain.playbook.js";

const CONTRACT = [
  {
    "state": "deciding",
    "sourceItem": "CAPTAIN-1",
    "player": "",
    "reads": [
      "parsedDecision"
    ],
    "wires": {
      "parsedDecision": [
        "parsedDecision"
      ]
    },
    "placeholders": []
  },
  {
    "state": "answeringCommand",
    "sourceItem": "CAPTAIN-2",
    "player": "",
    "reads": [],
    "wires": {},
    "placeholders": []
  },
  {
    "state": "reporting",
    "sourceItem": "CAPTAIN-3",
    "player": "",
    "reads": [],
    "wires": {},
    "placeholders": []
  }
];

describe("captain: prompt contract", () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

const CAPTAIN_SUBSTITUTED = {
  "deciding": [],
  "answeringCommand": [],
  "reporting": []
};

const composeCaptain = (
  playbook as unknown as {
    _internal: { composeCaptainPrompt: (input: unknown) => string };
  }
)._internal.composeCaptainPrompt;

  it('composes Captain prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composeCaptain,
        actor: 'captain',
      }),
    ).toEqual([]);
  });

  it('substitutes the Captain placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(
        findMachineConfig(fsm),
        composeCaptain,
        'captain',
      ),
    ).toEqual(CAPTAIN_SUBSTITUTED);
  });
});
