// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc link.
// FSM: ./captain.fsm.ts
// Player binding: none (the FSM has no delegated-player actor)
// Adjudication: LLM judge per Captain state
// Boss-event mapping: free-text judge classification

import PQueue from 'p-queue';
import { createActor, fromPromise } from 'xstate';
import {
  captainMachine,
  type CaptainInput,
  type CaptainOutput,
  type EnabledPlaybook,
  type PlaybookInput,
} from './captain.fsm.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlayerResult,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
} from '../../../src/runtime.js';
import {
  assertJsonSafe,
  combineAbortSignals,
  createNestedPlaybookBridge,
  normalizeError,
  normalizePlaybookSnapshot,
  snapshotJsonValue,
  snapshotPlaybookSession,
  validateCaptainResult,
  waitForPlaybookQuiescence,
} from '../../../src/xstate-runtime.js';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlayerResult,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
};

export interface PlaybookRuntimeOptions {
  readonly enabledPlaybooks: readonly EnabledPlaybook[];
}

type RuntimeEvent =
  | { readonly type: 'BOSS_INTENT'; readonly bossIntent: string }
  | {
      readonly type: 'BOSS_INTERRUPT';
      readonly targetId: 'routing';
      readonly bossIntent: string;
    }
  | {
      readonly type: 'BOSS_REPLY';
      readonly answer: string;
      readonly questionId?: string;
    };

type PendingQuestion = {
  readonly questionId: string;
  readonly player: string;
  readonly question: string;
};

const continuationPreamble =
  'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.';

function isRecord(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function requireNonEmptyString(value: unknown, path: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new TypeError(`${path} must be a non-empty string`);
  }
  return value;
}

function deterministicJson(value: unknown, path: string): string {
  const captured = snapshotJsonValue(value, path);
  return stringifyDeterministicJson(captured);
}

function stringifyDeterministicJson(value: JsonValue): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean' || typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'string') {
    const encoded = JSON.stringify(value);
    if (encoded === undefined) throw new TypeError('JSON string encoding failed');
    return encoded;
  }
  if (Array.isArray(value)) {
    return `[${value.map(stringifyDeterministicJson).join(',')}]`;
  }
  if (!isRecord(value)) throw new TypeError('JSON object encoding failed');
  return `{${Object.keys(value)
    .sort()
    .map((key) => {
      const encodedKey = JSON.stringify(key);
      if (encodedKey === undefined) throw new TypeError('JSON key encoding failed');
      return `${encodedKey}:${stringifyDeterministicJson(value[key])}`;
    })
    .join(',')}}`;
}

function continuationPrefix(input: Pick<CaptainInput, 'pendingBossQuestion' | 'bossReply'>): string {
  if (!input.pendingBossQuestion || input.bossReply === undefined) return '';
  return [
    continuationPreamble,
    '',
    'Boss question:',
    input.pendingBossQuestion.question,
    '',
    'Boss reply:',
    input.bossReply,
    '',
    '',
  ].join('\n');
}

function substituteCaptainPlaceholders(input: CaptainInput): string {
  const values: Readonly<Record<string, string>> = {
    'boss-intent': input.bossIntent,
    'enabled-playbooks': deterministicJson(input.enabledPlaybooks, 'Captain enabledPlaybooks'),
    'remaining-plan': deterministicJson(input.remainingPlan ?? [], 'Captain remainingPlan'),
    'completed-call-results': deterministicJson(
      input.completedCallResults ?? [],
      'Captain completedCallResults',
    ),
  };
  return input.prompt.replace(
    /<(boss-intent|enabled-playbooks|remaining-plan|completed-call-results)>/g,
    (_match, name: string) => values[name] ?? _match,
  );
}

export function composeCaptainPrompt(input: CaptainInput): string {
  return continuationPrefix(input) + substituteCaptainPlaceholders(input);
}

export function composePlayerPrompt(
  input: Pick<CaptainInput, 'prompt' | 'pendingBossQuestion' | 'bossReply'>,
): string {
  return continuationPrefix(input) + input.prompt;
}

function snapshotCatalog(value: unknown): readonly EnabledPlaybook[] {
  const captured = snapshotJsonValue(value, 'options.enabledPlaybooks');
  if (!Array.isArray(captured)) {
    throw new TypeError('options.enabledPlaybooks must be an array');
  }
  const ids = new Set<string>();
  const entries = captured.map((entry, index) => {
    if (!isRecord(entry)) {
      throw new TypeError(`options.enabledPlaybooks[${index}] must be an object`);
    }
    const keys = Object.keys(entry).sort();
    if (keys.length !== 3 || keys[0] !== 'command' || keys[1] !== 'id' || keys[2] !== 'intent') {
      throw new TypeError(`options.enabledPlaybooks[${index}] must contain exactly id, command, and intent`);
    }
    const id = requireNonEmptyString(entry.id, `options.enabledPlaybooks[${index}].id`);
    const command = requireNonEmptyString(entry.command, `options.enabledPlaybooks[${index}].command`);
    const intent = requireNonEmptyString(entry.intent, `options.enabledPlaybooks[${index}].intent`);
    if (ids.has(id)) throw new TypeError(`duplicate enabled playbook id ${id}`);
    ids.add(id);
    return Object.freeze({ id, command, intent });
  });
  return Object.freeze(entries);
}

function closeJsonCandidate(source: string): string {
  let output = '';
  let inString = false;
  let escaped = false;
  const stack: string[] = [];
  for (const character of source) {
    output += character;
    if (inString) {
      if (escaped) escaped = false;
      else if (character === '\\') escaped = true;
      else if (character === '"') inString = false;
      continue;
    }
    if (character === '"') inString = true;
    else if (character === '{') stack.push('}');
    else if (character === '[') stack.push(']');
    else if ((character === '}' || character === ']') && stack.at(-1) === character) stack.pop();
  }
  if (escaped) output += '\\';
  if (inString) output += '"';
  output = output.replace(/,\s*([}\]])/g, '$1');
  while (stack.length > 0) output += stack.pop();
  return output;
}

function balancedObject(source: string, start: number): string | undefined {
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const character = source[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (character === '\\') escaped = true;
      else if (character === '"') inString = false;
      continue;
    }
    if (character === '"') inString = true;
    else if (character === '{') depth += 1;
    else if (character === '}') {
      depth -= 1;
      if (depth === 0) return source.slice(start, index + 1);
    }
  }
  return undefined;
}

export function recoverJsonObject(text: string): Record<string, unknown> | undefined {
  for (let index = 0; index < text.length; index += 1) {
    if (text[index] !== '{') continue;
    const balanced = balancedObject(text, index);
    const candidates = balanced
      ? [balanced, balanced.replace(/,\s*([}\]])/g, '$1')]
      : [closeJsonCandidate(text.slice(index))];
    for (const candidate of candidates) {
      try {
        const parsed: unknown = JSON.parse(candidate);
        if (isRecord(parsed)) return parsed;
      } catch {
        // Try the repair for this candidate before moving forward.
      }
    }
  }
  return undefined;
}

function pendingQuestions(snapshot: unknown): readonly PendingQuestion[] {
  if (!isRecord(snapshot) || !isRecord(snapshot.context)) return [];
  const pending = snapshot.context.pendingBossQuestion;
  if (!isRecord(pending)) return [];
  if (
    typeof pending.questionId !== 'string' ||
    typeof pending.player !== 'string' ||
    typeof pending.question !== 'string'
  ) return [];
  return [{ questionId: pending.questionId, player: pending.player, question: pending.question }];
}

function classifierPrompt(state: PlaybookState, questions: readonly PendingQuestion[], text: string): string {
  const events = state.status === 'done' || state.stateId === 'ready' || state.stateId === 'failed'
    ? ['BOSS_INTENT with non-empty string bossIntent']
    : state.stateId === 'awaitBossReply'
      ? [
          'BOSS_REPLY with non-empty string answer and optional string questionId',
          'BOSS_INTENT with non-empty string bossIntent for a fresh directive',
          'BOSS_INTERRUPT with targetId exactly "routing" and non-empty string bossIntent for a fresh directive',
        ]
      : state.stateId === 'routing' || state.stateId === 'reassessing'
        ? ['BOSS_INTERRUPT with targetId exactly "routing" and non-empty string bossIntent']
        : [];
  return [
    'Classify the Boss text as exactly one allowed FSM event.',
    `Current state: ${state.stateId ?? JSON.stringify(state.value)}`,
    `Allowed events: ${events.length > 0 ? events.join('; ') : 'none'}`,
    ...(questions.length > 0
      ? ['Pending Boss questions:', deterministicJson(questions, 'pending Boss questions')]
      : []),
    `Boss text: ${text}`,
    'Return only one JSON object for the selected event, including its type and required payload fields.',
    'If no event applies, return {"type":"NO_ACTION"}.',
  ].join('\n');
}

function validateClassifiedEvent(
  value: Record<string, unknown>,
  state: PlaybookState,
  questions: readonly PendingQuestion[],
): RuntimeEvent | undefined {
  if (value.type === 'NO_ACTION') return undefined;
  if (value.type === 'BOSS_INTENT') {
    if (!(state.status === 'done' || state.stateId === 'ready' || state.stateId === 'failed' || state.stateId === 'awaitBossReply')) return undefined;
    if (Object.keys(value).some((key) => key !== 'type' && key !== 'bossIntent')) return undefined;
    return { type: 'BOSS_INTENT', bossIntent: requireNonEmptyString(value.bossIntent, 'classified bossIntent') };
  }
  if (value.type === 'BOSS_INTERRUPT') {
    if (state.stateId !== 'routing' && state.stateId !== 'reassessing' && state.stateId !== 'awaitBossReply') return undefined;
    if (value.targetId !== 'routing' || Object.keys(value).some((key) => !['type', 'targetId', 'bossIntent'].includes(key))) return undefined;
    return { type: 'BOSS_INTERRUPT', targetId: 'routing', bossIntent: requireNonEmptyString(value.bossIntent, 'classified bossIntent') };
  }
  if (value.type === 'BOSS_REPLY') {
    if (state.stateId !== 'awaitBossReply' || questions.length === 0) return undefined;
    if (Object.keys(value).some((key) => !['type', 'answer', 'questionId'].includes(key))) return undefined;
    const questionId = value.questionId === undefined && questions.length === 1
      ? questions[0].questionId
      : requireNonEmptyString(value.questionId, 'classified questionId');
    if (!questions.some((question) => question.questionId === questionId)) return undefined;
    return { type: 'BOSS_REPLY', answer: requireNonEmptyString(value.answer, 'classified answer'), questionId };
  }
  return undefined;
}

function requiredPayloadFields(description: string): readonly string[] {
  const fields = new Set<string>();
  for (const match of description.matchAll(/`([A-Za-z][A-Za-z0-9]*)(?::[^`]*)?`/g)) {
    if (match[1] !== 'guard') fields.add(match[1]);
  }
  return [...fields];
}

function validateAdjudication(value: Record<string, unknown>, input: CaptainInput): CaptainOutput {
  const guard = requireNonEmptyString(value.guard, 'adjudication guard');
  const description = input.result[guard];
  if (description === undefined) throw new TypeError(`undeclared adjudication guard ${guard}`);
  const required = requiredPayloadFields(description);
  const allowed = new Set(['guard', ...required]);
  if (Object.keys(value).some((key) => !allowed.has(key))) {
    throw new TypeError(`adjudication for ${guard} contains undeclared payload fields`);
  }
  for (const field of required) {
    if (!(field in value)) throw new TypeError(`adjudication guard ${guard} requires ${field}`);
    if (field === 'remainingPlan') {
      if (!Array.isArray(value[field])) throw new TypeError('remainingPlan must be an array');
      snapshotJsonValue(value[field], 'adjudication remainingPlan');
    } else if (!isNonEmptyPayloadString(value[field])) {
      throw new TypeError(`adjudication field ${field} must be a non-empty string`);
    }
  }
  const captured = snapshotJsonValue(value, 'Captain adjudication');
  return captured as unknown as CaptainOutput;
}

function isNonEmptyPayloadString(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

function adjudicatorPrompt(input: CaptainInput, prose: string): string {
  return [
    `Adjudicate direct Captain output for source item ${input.sourceItem}.`,
    'Captain output:',
    prose,
    'Valid results:',
    ...Object.entries(input.result).map(([guard, description]) => `${guard}: ${description}`),
    'Return only one JSON object with guard set to exactly one listed key and every payload field required by its description.',
  ].join('\n');
}

function eventForTrace(event: unknown): JsonValue {
  if (!isRecord(event)) return { type: 'unknown' };
  const result: Record<string, JsonValue> = {
    type: typeof event.type === 'string' ? event.type : 'unknown',
  };
  if ('output' in event) {
    try { result.output = snapshotJsonValue(event.output, 'transition event output'); }
    catch { result.output = { invalid: true }; }
  }
  if ('error' in event) result.error = snapshotJsonValue(normalizeError(event.error), 'transition error');
  return result;
}

function stateExtras(snapshot: unknown): Record<string, JsonValue> {
  if (!isRecord(snapshot) || !isRecord(snapshot.context)) return {};
  const extras: Record<string, JsonValue> = {};
  if (isRecord(snapshot.context.pendingBossQuestion)) {
    extras.pendingBossQuestion = snapshotJsonValue(snapshot.context.pendingBossQuestion, 'pending Boss question');
  }
  if (snapshot.context.lastError !== undefined) {
    extras.lastError = snapshotJsonValue(normalizeError(snapshot.context.lastError), 'lastError');
  }
  return extras;
}

export function createPlaybookRuntime(options: PlaybookRuntimeOptions): PlaybookRuntime {
  const enabledPlaybooks = snapshotCatalog(options.enabledPlaybooks);
  const emissionQueue = new PQueue({ concurrency: 1 });
  const agentQueue = new PQueue({ concurrency: 1 });
  let session: PlaybookSession | undefined;
  let actor: ReturnType<typeof createActor<typeof captainMachine>> | undefined;
  let nestedBridge: ReturnType<typeof createNestedPlaybookBridge<PlaybookInput>> | undefined;
  let boundarySignal: AbortSignal | undefined;
  let activeBoundary = false;
  let disposalPromise: Promise<void> | undefined;
  let disposed = false;
  let sequence = 0;
  let turnSequence = 0;
  let activeTraceTurnId: number | undefined;
  let callSequence = 0;
  const nestedCallTurns = new Map<string, number>();
  let controlError: unknown;
  let backgroundError: unknown;
  let previousState: PlaybookState | undefined;
  let suppressInspectionEmissions = false;

  const latchControl = (error: unknown): void => { if (controlError === undefined) controlError = error; };
  const latchBackground = (error: unknown): void => { if (backgroundError === undefined) backgroundError = error; };
  const requireSession = (): PlaybookSession => {
    if (!session || !actor || !nestedBridge) throw new Error('playbook runtime is not initialized');
    if (disposed || disposalPromise) throw new Error('playbook runtime is disposed');
    return session;
  };

  const enqueue = (work: () => Promise<void>): Promise<void> => emissionQueue.add(work);
  const trace = (
    type: PlaybookTraceEvent['type'],
    payload: unknown,
    identity: { turnId?: number; callId?: string } = {},
  ): Promise<void> => {
    const bound = session;
    if (!bound) return Promise.reject(new Error('trace emitted before session binding'));
    const capturedPayload = snapshotJsonValue(payload, `trace ${type} payload`);
    sequence += 1;
    const event: PlaybookTraceEvent = {
      schemaVersion: 2,
      sessionId: bound.sessionId,
      playbookId: bound.playbookId,
      rootSessionId: bound.rootSessionId,
      ...(bound.parentSessionId === undefined ? {} : { parentSessionId: bound.parentSessionId }),
      ...(bound.parentCallId === undefined ? {} : { parentCallId: bound.parentCallId }),
      depth: bound.depth,
      sequence,
      timestamp: Date.now(),
      type,
      ...(identity.turnId === undefined ? {} : { turnId: identity.turnId }),
      ...(identity.callId === undefined ? {} : { callId: identity.callId }),
      payload: capturedPayload,
    };
    return enqueue(() => bound.ports.emitTelemetry({ topic: 'playbook.trace', payload: event }));
  };

  const drain = async (): Promise<void> => {
    await emissionQueue.onIdle();
    if (backgroundError !== undefined) throw backgroundError;
  };

  const statePayload = (state: PlaybookState): Record<string, unknown> => ({
    state,
    ...(state.stateId === undefined ? {} : { stateId: state.stateId }),
  });

  const emitStatus = (message: string, data?: unknown, state?: PlaybookState): void => {
    const capturedData = data === undefined ? undefined : snapshotJsonValue(data, 'status data');
    const descriptor = state ?? (actor && nestedBridge
      ? normalizePlaybookSnapshot(actor.getSnapshot(), { pendingCall: nestedBridge.getPendingCall() })
      : undefined);
    const payload = {
      message,
      ...(capturedData === undefined ? {} : { data: capturedData }),
      ...(descriptor === undefined ? {} : statePayload(descriptor)),
    };
    void trace('status.emitted', payload, activeTraceTurnId === undefined ? {} : { turnId: activeTraceTurnId }).catch(latchBackground);
    const bound = session;
    if (bound) void enqueue(() => bound.ports.emitStatus(message, capturedData)).catch(latchBackground);
  };

  const inspect = (inspectionEvent: unknown): void => {
    try {
      if (!isRecord(inspectionEvent) || inspectionEvent.type !== '@xstate.snapshot') return;
      if (inspectionEvent.actorRef !== actor) return;
      if (suppressInspectionEmissions) return;
      const snapshot = inspectionEvent.snapshot;
      const state = normalizePlaybookSnapshot(snapshot, { pendingCall: nestedBridge?.getPendingCall() });
      const payload = {
        from: previousState?.value ?? null,
        to: state.value,
        event: eventForTrace(inspectionEvent.event),
        ...(previousState === undefined ? {} : { previousState }),
        state,
        ...stateExtras(snapshot),
      };
      void trace('fsm.transition', payload, activeBoundary && activeTraceTurnId !== undefined ? { turnId: activeTraceTurnId } : {}).catch(latchBackground);
      const bound = session;
      if (bound) void enqueue(() => bound.ports.emitTelemetry({ topic: 'playbook.fsm.state', payload: snapshotJsonValue(payload, 'FSM telemetry') })).catch(latchBackground);
      if (state.stateId !== 'ready' && state.stateId !== 'done') {
        emitStatus(state.stateId === 'failed' && isRecord(snapshot) && isRecord(snapshot.context)
          ? `Captain entered failed: ${normalizeError(snapshot.context.lastError).message}`
          : `Captain entered ${state.stateId ?? JSON.stringify(state.value)}`, state, state);
      }
      previousState = state;
    } catch (error) {
      latchBackground(error);
    }
  };

  const nextCallId = (): string => {
    const bound = session;
    if (!bound) throw new Error('cannot allocate call id before init');
    callSequence += 1;
    return `${bound.sessionId}:call:${callSequence}`;
  };

  const callJudge = async (
    prompt: string,
    purpose: 'boss-input-classification' | 'captain-output-adjudication',
    signal: AbortSignal,
    turnId?: number,
    stateId?: string,
  ): Promise<string> => agentQueue.add(async () => {
    if (signal.aborted) throw signal.reason ?? new Error('judge call aborted');
    const bound = requireSession();
    const callId = nextCallId();
    await drain();
    try {
      await trace('judge.call.started', { prompt, purpose, ...(stateId === undefined ? {} : { stateId }) }, { ...(turnId === undefined ? {} : { turnId }), callId });
      await drain();
    } catch (startError) {
      try { await trace('judge.call.finished', { prompt, purpose, ...(stateId === undefined ? {} : { stateId }), status: signal.aborted ? 'aborted' : 'error', error: normalizeError(startError) }, { ...(turnId === undefined ? {} : { turnId }), callId }); await emissionQueue.onIdle(); } catch {}
      throw startError;
    }
    let finishAttempted = false;
    try {
      const reply = await bound.ports.callJudge(prompt, signal);
      if (signal.aborted) throw signal.reason ?? new Error('judge call aborted');
      if (typeof reply !== 'string') throw new TypeError('judge reply must be a string');
      finishAttempted = true;
      await trace('judge.call.finished', { prompt, purpose, ...(stateId === undefined ? {} : { stateId }), status: 'ok', reply }, { ...(turnId === undefined ? {} : { turnId }), callId });
      await drain();
      return reply;
    } catch (error) {
      if (!finishAttempted) {
        try { await trace('judge.call.finished', { prompt, purpose, ...(stateId === undefined ? {} : { stateId }), status: signal.aborted ? 'aborted' : 'error', error: normalizeError(error) }, { ...(turnId === undefined ? {} : { turnId }), callId }); await emissionQueue.onIdle(); } catch (finishError) { latchBackground(finishError); }
      }
      throw error;
    }
  });

  const providedCaptain = fromPromise<CaptainOutput, CaptainInput>(async ({ input, signal }) => {
    const bound = requireSession();
    await drain();
    const combined = combineAbortSignals(signal, boundarySignal);
    const prompt = composeCaptainPrompt(input);
    const callId = nextCallId();
    const visibility = 'visible' as const;
    try {
      await trace('captain.call.started', { prompt, visibility, stateId: input.stateId, sourceItem: input.sourceItem }, { ...(activeTraceTurnId === undefined ? {} : { turnId: activeTraceTurnId }), callId });
      await drain();
    } catch (startError) {
      try { await trace('captain.call.finished', { prompt, visibility, stateId: input.stateId, sourceItem: input.sourceItem, status: combined.aborted ? 'aborted' : 'error', error: normalizeError(startError) }, { ...(activeTraceTurnId === undefined ? {} : { turnId: activeTraceTurnId }), callId }); await emissionQueue.onIdle(); } catch {}
      latchControl(startError);
      throw startError;
    }
    let result: CaptainResult;
    let finishAttempted = false;
    try {
      const raw = await agentQueue.add(async () => {
        if (combined.aborted) {
          throw combined.reason ?? new Error('Captain call aborted');
        }
        const value = await bound.ports.callCaptain(prompt, combined, {
          visibility,
        });
        if (combined.aborted) {
          throw combined.reason ?? new Error('Captain call aborted');
        }
        return value;
      });
      result = validateCaptainResult(raw);
      const resultError = result.status !== 'ok'
        ? new Error(result.error ?? `Captain call ${result.status}`)
        : result.finalText === undefined
          ? new Error('Captain call did not return finalText')
          : undefined;
      if (resultError !== undefined && !combined.aborted) latchControl(resultError);
      const reportedError = result.error ?? resultError;
      const finishPayload = {
        prompt,
        visibility,
        stateId: input.stateId,
        sourceItem: input.sourceItem,
        status: result.status,
        ...(result.finalText === undefined ? {} : { finalText: result.finalText }),
        ...(reportedError === undefined ? {} : { error: normalizeError(reportedError) }),
      };
      finishAttempted = true;
      await trace('captain.call.finished', finishPayload, { ...(activeTraceTurnId === undefined ? {} : { turnId: activeTraceTurnId }), callId });
      await drain();
      if (resultError !== undefined) throw resultError;
    } catch (error) {
      if (!finishAttempted) {
        try { await trace('captain.call.finished', { prompt, visibility, stateId: input.stateId, sourceItem: input.sourceItem, status: combined.aborted ? 'aborted' : 'error', error: normalizeError(error) }, { ...(activeTraceTurnId === undefined ? {} : { turnId: activeTraceTurnId }), callId }); await emissionQueue.onIdle(); } catch (finishError) { latchBackground(finishError); }
      }
      if (!combined.aborted) latchControl(error);
      throw error;
    }
    if (result.finalText === undefined) throw new Error('Captain result invariant violated');
    try {
      const reply = await callJudge(adjudicatorPrompt(input, result.finalText), 'captain-output-adjudication', combined, activeTraceTurnId, input.stateId);
      const object = recoverJsonObject(reply);
      if (!object) throw new TypeError('Captain adjudicator returned no recoverable JSON object');
      return validateAdjudication(object, input);
    } catch (error) {
      if (!combined.aborted) latchControl(error);
      throw error;
    }
  });

  const makeBridge = () => createNestedPlaybookBridge<PlaybookInput>({
    nextCallId,
    getBoundarySignal: () => boundarySignal,
    callPlaybook: (request, signal) => requireSession().ports.callPlaybook(request, signal),
    emitStarted: async (event) => {
      if (activeTraceTurnId !== undefined) nestedCallTurns.set(event.callId, activeTraceTurnId);
      await trace('playbook.call.started', {
        stateId: event.stateId,
        playbookId: event.playbookId,
        text: event.text,
      }, { ...(activeTraceTurnId === undefined ? {} : { turnId: activeTraceTurnId }), callId: event.callId });
    },
    emitFinished: async (event) => {
      const callTurnId = nestedCallTurns.get(event.callId);
      try {
        await trace('playbook.call.finished', {
          stateId: event.stateId,
          playbookId: event.playbookId,
          text: event.text,
          result: event.result,
        }, { ...(callTurnId === undefined ? {} : { turnId: callTurnId }), callId: event.callId });
      } finally {
        nestedCallTurns.delete(event.callId);
      }
    },
    drain,
    bindResumeSignal: (signal) => { boundarySignal = signal; },
    onControlPlaneError: latchControl,
    onBackgroundError: latchBackground,
  });

  const constructActor = (bound: PlaybookSession) => {
    nestedBridge = makeBridge();
    return createActor(
      captainMachine.provide({
        actors: {
          captain: providedCaptain,
          playbook: nestedBridge.actorLogic,
        },
      }),
      {
        input: { selfPlaybookId: bound.playbookId, enabledPlaybooks },
        inspect,
      },
    );
  };

  const currentState = (): PlaybookState => {
    if (!actor || !nestedBridge) throw new Error('playbook runtime is not initialized');
    return normalizePlaybookSnapshot(actor.getSnapshot(), { pendingCall: nestedBridge.getPendingCall() });
  };

  const outcome = (): PlaybookRunResult => {
    if (!actor || !nestedBridge) throw new Error('playbook runtime is not initialized');
    const snapshot = actor.getSnapshot();
    const state = normalizePlaybookSnapshot(snapshot, { pendingCall: nestedBridge.getPendingCall() });
    const pendingCall = nestedBridge.getPendingCall();
    if (pendingCall) return { outcome: 'suspended', state, pendingCall };
    if (state.status === 'done') {
      const output = snapshot.output;
      if (output === undefined) return { outcome: 'terminal', state };
      assertJsonSafe(output, 'machine output');
      return { outcome: 'terminal', state, output: snapshotJsonValue(output, 'machine output') };
    }
    if (boundarySignal?.aborted) return { outcome: 'aborted', state, error: normalizeError(boundarySignal.reason) };
    if (state.stateId === 'failed') {
      const context = snapshot.context;
      return context.lastError === undefined
        ? { outcome: 'failed', state }
        : { outcome: 'failed', state, error: normalizeError(context.lastError) };
    }
    return { outcome: 'quiescent', state };
  };

  const settlementPayload = (result: PlaybookRunResult): Record<string, unknown> => ({
    outcome: result.outcome,
    ...statePayload(result.state),
    ...('pendingCall' in result ? { pendingCall: result.pendingCall } : {}),
    ...('output' in result && result.output !== undefined ? { output: result.output } : {}),
    ...('error' in result && result.error !== undefined ? { error: result.error } : {}),
  });

  const completeBoundary = async (options: {
    turnId?: number;
    knownResult?: PlaybookRunResult;
    operationError?: unknown;
  }): Promise<PlaybookRunResult> => {
    if (!actor || !nestedBridge) throw new Error('playbook runtime is not initialized');
    let waitError: unknown;
    try {
      await waitForPlaybookQuiescence(actor, { pendingCalls: nestedBridge });
    } catch (error) {
      waitError = error;
    }
    let drainError: unknown;
    try {
      await drain();
    } catch (error) {
      drainError = error;
    }

    const latchedControlError = controlError;
    const nonAbortError = latchedControlError ?? drainError;
    const aborted = nonAbortError === undefined && boundarySignal?.aborted === true;
    const operationFailure = waitError ?? options.operationError;
    const result = nonAbortError !== undefined
      ? { outcome: 'failed' as const, state: currentState(), error: normalizeError(nonAbortError) }
      : aborted
        ? {
            outcome: 'aborted' as const,
            state: currentState(),
            error: normalizeError(boundarySignal?.reason ?? operationFailure),
          }
        : operationFailure !== undefined
          ? { outcome: 'failed' as const, state: currentState(), error: normalizeError(operationFailure) }
          : (options.knownResult ?? outcome());

    let settlementError: unknown;
    if (options.turnId !== undefined) {
      try {
        await trace('boss.input.settled', settlementPayload(result), { turnId: options.turnId });
        await emissionQueue.onIdle();
      } catch (error) {
        settlementError = error;
      }
    }

    if (latchedControlError !== undefined) throw latchedControlError;
    if (drainError !== undefined) throw drainError;
    if (!aborted && waitError !== undefined) throw waitError;
    if (!aborted && options.operationError !== undefined) throw options.operationError;
    if (settlementError !== undefined) throw settlementError;
    return result;
  };

  const beginBoundary = (signal: AbortSignal): void => {
    requireSession();
    if (activeBoundary) throw new Error('another playbook runtime boundary is active');
    activeBoundary = true;
    boundarySignal = signal;
    controlError = undefined;
    backgroundError = undefined;
  };

  const endBoundary = (): void => {
    activeBoundary = false;
    boundarySignal = undefined;
    activeTraceTurnId = undefined;
    controlError = undefined;
    backgroundError = undefined;
  };

  const runtime: PlaybookRuntime = {
    async init(inputSession) {
      if (session || actor || disposed || disposalPromise) throw new Error('playbook runtime cannot be initialized again');
      const bound = snapshotPlaybookSession(inputSession);
      session = bound;
      try {
        suppressInspectionEmissions = false;
        const initializedActor = constructActor(bound);
        actor = initializedActor;
        await trace('session.started', statePayload(currentState()));
        await drain();
        initializedActor.start();
        await drain();
      } catch (error) {
        const failedActor = actor;
        const finalState = actor && nestedBridge ? currentState() : undefined;
        suppressInspectionEmissions = true;
        try { failedActor?.stop(); } catch {}
        try { await nestedBridge?.dispose(); } catch {}
        try { await agentQueue.onIdle(); await emissionQueue.onIdle(); } catch {}
        try {
          await trace('session.disposed', finalState === undefined ? {} : statePayload(finalState));
          await emissionQueue.onIdle();
        } catch {}
        nestedCallTurns.clear();
        emissionQueue.clear();
        agentQueue.clear();
        actor = undefined;
        nestedBridge = undefined;
        session = undefined;
        boundarySignal = undefined;
        activeBoundary = false;
        activeTraceTurnId = undefined;
        controlError = undefined;
        backgroundError = undefined;
        previousState = undefined;
        suppressInspectionEmissions = false;
        sequence = 0;
        turnSequence = 0;
        callSequence = 0;
        throw error;
      }
    },

    async handleBossInput(turn) {
      beginBoundary(turn.signal);
      turnSequence += 1;
      const turnId = turnSequence;
      activeTraceTurnId = turnId;
      let knownResult: PlaybookRunResult | undefined;
      let operationError: unknown;
      try {
        try {
          await trace('boss.input.received', { text: turn.text }, { turnId });
          await drain();
          if (turn.text.trim().length === 0) {
            knownResult = { outcome: 'no-action', state: currentState() };
          } else {
            const snapshot = actor?.getSnapshot();
            if (!snapshot) throw new Error('playbook runtime actor is unavailable');
            const state = currentState();
            const questions = pendingQuestions(snapshot);
            const reply = await callJudge(
              classifierPrompt(state, questions, turn.text),
              'boss-input-classification',
              turn.signal,
              turnId,
              state.stateId,
            );
            let event: RuntimeEvent | undefined;
            try {
              const object = recoverJsonObject(reply);
              if (object?.type === 'NO_ACTION' && Object.keys(object).length === 1) {
                knownResult = { outcome: 'no-action', state: currentState() };
              } else {
                event = object ? validateClassifiedEvent(object, state, questions) : undefined;
                if (!event) throw new TypeError('Boss classification was malformed');
              }
            } catch (error) {
              emitStatus(`Boss input was not actionable: ${normalizeError(error).message}`, undefined, currentState());
              knownResult = { outcome: 'no-action', state: currentState() };
            }
            if (event) {
              const rootActor = actor;
              if (!rootActor) throw new Error('playbook runtime actor is unavailable');
              let activeActor = rootActor;
              if (rootActor.getSnapshot().status === 'done') {
                rootActor.stop();
                await nestedBridge?.dispose();
                previousState = undefined;
                const reconstructedActor = constructActor(requireSession());
                actor = reconstructedActor;
                activeActor = reconstructedActor;
                reconstructedActor.start();
                await drain();
              }
              activeActor.send(event);
            }
          }
        } catch (error) {
          operationError = error;
          if (!turn.signal.aborted) latchControl(error);
        }
        return await completeBoundary({ turnId, knownResult, operationError });
      } finally {
        try { await emissionQueue.onIdle(); } finally { endBoundary(); }
      }
    },

    async resumePlaybookCall(input) {
      beginBoundary(input.signal);
      activeTraceTurnId = nestedCallTurns.get(input.callId);
      let operationError: unknown;
      try {
        try {
          if (!nestedBridge) throw new Error('nested playbook bridge is unavailable');
          await nestedBridge.resume(input);
        } catch (error) {
          operationError = error;
          if (!input.signal.aborted) latchControl(error);
        }
        return await completeBoundary({ operationError });
      } finally {
        try { await emissionQueue.onIdle(); } finally { endBoundary(); }
      }
    },

    dispose() {
      if (activeBoundary) return Promise.reject(new Error('cannot dispose during an active runtime boundary'));
      if (disposalPromise) return disposalPromise;
      if (disposed) return Promise.resolve();
      disposalPromise = (async () => {
        const bound = session;
        if (!bound) { disposed = true; return; }
        let firstError: unknown;
        const finalState = actor ? currentState() : undefined;
        try { actor?.stop(); } catch (error) { firstError = error; }
        try { await nestedBridge?.dispose(); } catch (error) { firstError ??= error; }
        try { await agentQueue.onIdle(); await drain(); } catch (error) { firstError ??= error; }
        try {
          await trace('session.disposed', finalState === undefined ? {} : statePayload(finalState));
          await emissionQueue.onIdle();
        } catch (error) { firstError ??= error; }
        nestedCallTurns.clear();
        actor = undefined;
        nestedBridge = undefined;
        session = undefined;
        disposed = true;
        if (firstError !== undefined) throw firstError;
      })();
      return disposalPromise;
    },
  };

  return runtime;
}

const factory: PlaybookRuntimeFactory<PlaybookRuntimeOptions> = createPlaybookRuntime;
export default factory;

export const _internal = Object.freeze({
  composePlayerPrompt,
  composeCaptainPrompt,
  recoverJsonObject,
});
