// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from "./.slc-verify/verify.js";
import * as fsm from "./captain.fsm.js";

const PINNED = {
  "initial": "ready",
  "captain": [
    {
      "state": "routing",
      "actor": "captain",
      "sourceItem": "CAPTAIN-1",
      "player": "",
      "resultKeys": [
        "delegation",
        "direct",
        "needsBossReply",
        "question"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "done",
          "guarded": true
        },
        {
          "index": 1,
          "target": "awaitBossReply",
          "guarded": true
        },
        {
          "index": 2,
          "target": "callPlaybook",
          "guarded": true
        },
        {
          "index": 3,
          "target": "awaitBossReply",
          "guarded": true
        },
        {
          "index": 4,
          "target": "failed",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    },
    {
      "state": "reassessment",
      "actor": "captain",
      "sourceItem": "CAPTAIN-3",
      "player": "",
      "resultKeys": [
        "continuing",
        "final",
        "followUpQuestion",
        "needsBossReply"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "done",
          "guarded": true
        },
        {
          "index": 1,
          "target": "awaitBossReply",
          "guarded": true
        },
        {
          "index": 2,
          "target": "callPlaybook",
          "guarded": true
        },
        {
          "index": 3,
          "target": "awaitBossReply",
          "guarded": true
        },
        {
          "index": 4,
          "target": "failed",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    }
  ],
  "quiescent": [
    {
      "state": "ready",
      "final": false,
      "on": {
        "BOSS_INTENT": [
          {
            "index": 0,
            "target": "routing",
            "guarded": true
          }
        ]
      }
    },
    {
      "state": "awaitBossReply",
      "final": false,
      "on": {
        "BOSS_REPLY": [
          {
            "index": 0,
            "target": "routing",
            "guarded": true
          },
          {
            "index": 1,
            "target": "reassessment",
            "guarded": true
          }
        ],
        "BOSS_INTENT": [
          {
            "index": 0,
            "target": "routing",
            "guarded": true
          }
        ]
      }
    },
    {
      "state": "failed",
      "final": false,
      "on": {
        "BOSS_INTENT": [
          {
            "index": 0,
            "target": "routing",
            "guarded": true
          }
        ]
      }
    },
    {
      "state": "done",
      "final": true,
      "on": {}
    }
  ],
  "rootOn": {
    "BOSS_INTERRUPT": [
      {
        "index": 0,
        "target": "routing",
        "guarded": true
      }
    ]
  },
  "interruptTargets": [
    "routing"
  ],
  "playbook": [
    {
      "state": "callPlaybook",
      "playbookIdContext": "nextPlaybookId",
      "textContext": "nextPlaybookInput",
      "sourceItem": "CAPTAIN-2",
      "onDone": [
        {
          "index": 0,
          "target": "reassessment",
          "guarded": true
        },
        {
          "index": 1,
          "target": "failed",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "reassessment",
          "guarded": true
        },
        {
          "index": 1,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    }
  ]
};

describe("captain: FSM introspection", () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
