// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from "./.slc-verify/verify.js";
import * as fsm from "./captain.fsm.js";
import * as playbook from "./captain.playbook.js";

const CONTRACT = [
  {
    "state": "routing",
    "sourceItem": "CAPTAIN-1",
    "player": "",
    "reads": [
      "bossIntent",
      "bossReply",
      "enabledPlaybooks",
      "pendingBossQuestion"
    ],
    "wires": {
      "bossIntent": [
        "bossIntent"
      ],
      "enabledPlaybooks": [
        "enabledPlaybooks"
      ],
      "pendingBossQuestion": [
        "pendingBossQuestion"
      ],
      "bossReply": [
        "bossReply"
      ]
    },
    "placeholders": [
      "<boss-intent>",
      "<enabled-playbooks>"
    ]
  },
  {
    "state": "reassessment",
    "sourceItem": "CAPTAIN-3",
    "player": "",
    "reads": [
      "bossIntent",
      "bossReply",
      "completedCallResults",
      "enabledPlaybooks",
      "pendingBossQuestion",
      "remainingPlan"
    ],
    "wires": {
      "bossIntent": [
        "bossIntent"
      ],
      "enabledPlaybooks": [
        "enabledPlaybooks"
      ],
      "remainingPlan": [
        "remainingPlan"
      ],
      "completedCallResults": [
        "completedCallResults"
      ],
      "pendingBossQuestion": [
        "pendingBossQuestion"
      ],
      "bossReply": [
        "bossReply"
      ]
    },
    "placeholders": [
      "<boss-intent>",
      "<enabled-playbooks>",
      "<remaining-plan>",
      "<completed-call-results>"
    ]
  }
];

describe("captain: prompt contract", () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

const CAPTAIN_SUBSTITUTED = {
  "routing": [
    "<boss-intent>",
    "<enabled-playbooks>"
  ],
  "reassessment": [
    "<boss-intent>",
    "<enabled-playbooks>",
    "<remaining-plan>",
    "<completed-call-results>"
  ]
};

const composeCaptain = (
  playbook as unknown as {
    _internal: { composeCaptainPrompt: (input: unknown) => string };
  }
)._internal.composeCaptainPrompt;

  it('composes Captain prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composeCaptain,
        actor: 'captain',
      }),
    ).toEqual([]);
  });

  it('substitutes the Captain placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(
        findMachineConfig(fsm),
        composeCaptain,
        'captain',
      ),
    ).toEqual(CAPTAIN_SUBSTITUTED);
  });
});
