// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from "./.slc-verify/verify.js";
import * as fsm from "./inspect.fsm.js";
import * as playbook from "./inspect.playbook.js";

const CONTRACT = [
  {
    "state": "inspecting",
    "sourceItem": "INSPECT-1",
    "player": "",
    "role": "inspector",
    "reads": [
      "bossReply",
      "discussionContext",
      "inspectionRequest",
      "pendingBossQuestion"
    ],
    "wires": {
      "inspectionRequest": [
        "inspectionRequest"
      ],
      "discussionContext": [
        "discussionContext"
      ]
    },
    "placeholders": [
      "<inspection-request>",
      "<discussion-context>"
    ]
  }
] as const;
const SCHEMA_FINDINGS: readonly string[] = [];

describe("inspect: prompt contract", () => {
  it('uses consistent artifact-schema evidence', () => {
    expect(SCHEMA_FINDINGS).toEqual([]);
  });

  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

const PLAYER_SUBSTITUTED = {
  "inspecting": [
    "<inspection-request>",
    "<discussion-context>"
  ]
} as const;

const composePlayer = (
  playbook as unknown as {
    _internal: { composePlayerPrompt: (input: unknown) => string };
  }
)._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composePlayer,
        actor: 'player',
        artifactSchema: 3,
      }),
    ).toEqual([]);
  });

  it('substitutes the player placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(
        findMachineConfig(fsm),
        composePlayer,
        'player',
      ),
    ).toEqual(PLAYER_SUBSTITUTED);
  });
});
