// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./pr.fsm.ts
// Role metadata: Coder→coder (canonical local role)
// Boss event:    deterministic START_PR entry; exact Boss text becomes
//                callerInput; pending Coder questions retain BOSS_REPLY
// Adjudication:  LLM judge for the one Coder state; coderOutput is carried
//                verbatim; pullRequest and pullRequestUrl are judge-authored
//                semantic fields; every arm is governed `unchanged`
// Scripts:       five DR-016 script states run through the shared factory's
//                `sh -c` actor in the optional `cwd` option
// Nested calls:  literal code target through the shared bridge
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  composePlayerContinuation,
  snapshotJsonValue,
  type PlaybookPlayerInput,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import {
  prMachine,
  type PlayerInput,
  type PrInput,
} from './pr.fsm.js';
import type { PlaybookHostConstructionCapabilities } from '../code.playbook/playbook-captain.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

/**
 * PR's per-run options. The machine reads no input of its own; the one
 * linker-owned option is the working directory its five script states run
 * in (slc/link.md §Script execution). Absent, the process working directory.
 */
export type PrPlaybookOptions = PrInput & {
  readonly cwd?: string;
};
export type PrPlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<PrPlaybookOptions, object>['hostCapabilities'];

const OPTION_KEYS = new Set(['cwd']);
const PLACEHOLDER = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g;

const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'coderOutput',
]);
// Every failure terminal leaves the delivery unfinished: no pull request is
// guaranteed to exist after notPublished, and the other four leave it open.
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set([
  'notPublished',
  'fixFailed',
  'fixNotPublished',
  'checksStillFailing',
  'mergeRefused',
]);

function snapshotPrOptions(value: unknown): PrPlaybookOptions {
  const captured = snapshotJsonValue(value, 'PR runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('PR runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const [key, option] of Object.entries(record)) {
    if (!OPTION_KEYS.has(key)) {
      throw new TypeError(`PR runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string' || option.length === 0) {
      throw new TypeError(`PR runtime options.${key} must be a non-empty string`);
    }
  }
  return captured as unknown as PrPlaybookOptions;
}

function placeholderField(token: string): string {
  if (token === '#') return 'irNumber';
  return token.replace(/-([A-Za-z0-9_$])/g, (_match, next: string) =>
    next.toUpperCase(),
  );
}

function quotedContinuation(value: string): string {
  return value.replaceAll('\n', '\n> ');
}

/**
 * Preserve the authored Markdown quote marker around every line of the
 * relayed caller input. The generic composer preserves the marker itself;
 * PR's override additionally keeps a multiline value inside that quote.
 */
function composePlayerPrompt(input: PlayerInput, resuming = false): string {
  const fields = input as unknown as Record<string, unknown>;
  const body = input.prompt.replace(
    PLACEHOLDER,
    (match: string, token: string, offset: number, source: string) => {
      const value = fields[placeholderField(token)];
      if (typeof value !== 'string') return match;
      const lineStart = source.lastIndexOf('\n', offset - 1) + 1;
      return source.slice(lineStart, offset).startsWith('> ')
        ? quotedContinuation(value)
        : value;
    },
  );
  return composePlayerContinuation(input, body, resuming);
}

export const _internal = {
  composePlayerPrompt,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
};

const runtimeSpec = {
  label: 'PR',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotPrOptions,
  entryEvent: {
    type: 'START_PR',
    textField: 'callerInput',
    // `startPr` copies the entry text here, so the failure-state retry reads
    // it back from the persisted machine snapshot and survives a continued
    // session (DR-034).
    contextField: 'callerInput',
  },
  roleStates: {
    openPullRequest: {
      role: 'coder',
      label: 'Coder is publishing the branch and opening its pull request.',
    },
  },
  // DR-050: PR owns no repository commit — pushing a branch and opening a
  // pull request move only remote-tracking refs and forge state, so every
  // Coder outcome is governed with the `unchanged` repository disposition.
  // The pull request number and URL are judge-authored semantic fields; the
  // Coder's report on a refused publication is carried verbatim.
  outcomeAuthority: {
    governedPlayerStates: {
      openPullRequest: {
        opened: {
          fields: { pullRequest: 'semantic', pullRequestUrl: 'semantic' },
          repositoryDisposition: 'unchanged',
        },
        notPublished: {
          fields: { coderOutput: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
      },
    },
  },
  composePlayerPrompt: (input: PlaybookPlayerInput, _identity, resuming) =>
    composePlayerPrompt(input as PlayerInput, resuming),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  controlContextFields: [],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: ['callerInput', 'answer', 'questionId'],
} satisfies XStatePlaybookRuntimeSpecV3<PrPlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    PrPlaybookOptions,
    PrPlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  PrPlaybookOptions,
  PrPlaybookHostCapabilities
>(prMachine, runtimeSpec);

export default createPlaybookRuntime;
