// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from "./.slc-verify/verify.js";
import * as fsm from "./inspect.fsm.js";

const PINNED = {
  "initial": "ready",
  "captain": [
    {
      "state": "inspecting",
      "actor": "player",
      "sourceItem": "INSPECT-1",
      "player": "",
      "role": "inspector",
      "resultKeys": [
        "completed",
        "needsBossReply",
        "unavailable"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "complete",
          "guarded": true
        },
        {
          "index": 1,
          "target": "unavailable",
          "guarded": true
        },
        {
          "index": 2,
          "target": "awaitBossReply",
          "guarded": true
        },
        {
          "index": 3,
          "target": "failed",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    }
  ],
  "quiescent": [
    {
      "state": "ready",
      "final": false,
      "on": {
        "START": [
          {
            "index": 0,
            "target": "inspecting",
            "guarded": true
          }
        ]
      }
    },
    {
      "state": "awaitBossReply",
      "final": false,
      "on": {
        "BOSS_REPLY": [
          {
            "index": 0,
            "target": "inspecting",
            "guarded": true
          },
          {
            "index": 1,
            "target": "failed",
            "guarded": false
          }
        ]
      }
    },
    {
      "state": "complete",
      "final": true,
      "on": {}
    },
    {
      "state": "unavailable",
      "final": true,
      "on": {}
    },
    {
      "state": "failed",
      "final": false,
      "on": {
        "START": [
          {
            "index": 0,
            "target": "inspecting",
            "guarded": true
          }
        ]
      }
    }
  ],
  "rootOn": {},
  "interruptTargets": []
} as const;

describe("inspect: FSM introspection", () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
