// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./branch.fsm.ts
// Role metadata: Coder→coder (canonical local role)
// Boss event:    deterministic START_BRANCH entry; exact Boss text becomes
//                callerInput; pending Coder questions retain BOSS_REPLY
// Adjudication:  LLM judge for the one Coder state; coderOutput is carried
//                verbatim; baseRevision is receipt-owned effect evidence —
//                the unchanged receipt's observed HEAD — never taken from
//                Coder's prose
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  composePlayerContinuation,
  snapshotJsonValue,
  type PlaybookPlayerInput,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import {
  branchMachine,
  type BranchInput,
  type PlayerInput,
} from './branch.fsm.js';
import type { PlaybookHostConstructionCapabilities } from '../code.playbook/playbook-captain.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

export type BranchPlaybookOptions = BranchInput;
export type BranchPlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<BranchPlaybookOptions, object>['hostCapabilities'];

const PLACEHOLDER = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g;

const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'coderOutput',
]);
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set(['refused']);

function snapshotBranchOptions(value: unknown): BranchPlaybookOptions {
  const captured = snapshotJsonValue(value, 'BRANCH runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('BRANCH runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const key of Object.keys(record)) {
    throw new TypeError(`BRANCH runtime options.${key} is not declared`);
  }
  return captured as unknown as BranchPlaybookOptions;
}

function placeholderField(token: string): string {
  if (token === '#') return 'irNumber';
  return token.replace(/-([A-Za-z0-9_$])/g, (_match, next: string) =>
    next.toUpperCase(),
  );
}

function quotedContinuation(value: string): string {
  return value.replaceAll('\n', '\n> ');
}

/**
 * Preserve authored Markdown quote markers around every line of relayed
 * runtime text. The generic composer preserves the marker itself; BRANCH's
 * override additionally keeps a multiline caller input inside that quote.
 */
function composePlayerPrompt(input: PlayerInput, resuming = false): string {
  const fields = input as unknown as Record<string, unknown>;
  const body = input.prompt.replace(
    PLACEHOLDER,
    (match: string, token: string, offset: number, source: string) => {
      const value = fields[placeholderField(token)];
      if (typeof value !== 'string') return match;
      const lineStart = source.lastIndexOf('\n', offset - 1) + 1;
      const literal = source.slice(lineStart, offset);
      return literal.startsWith('> ') ? quotedContinuation(value) : value;
    },
  );
  return composePlayerContinuation(input, body, resuming);
}

export const _internal = {
  composePlayerPrompt,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
};

const runtimeSpec = {
  label: 'BRANCH',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotBranchOptions,
  entryEvent: {
    type: 'START_BRANCH',
    textField: 'callerInput',
    // `startBranch` copies the entry text here, so the failure-state retry
    // reads it back from the persisted machine snapshot and survives a
    // continued session (DR-034).
    contextField: 'callerInput',
  },
  roleStates: {
    createBranch: {
      role: 'coder',
      label:
        'Coder is reading the named issue and creating and checking out a new branch at the current commit.',
    },
  },
  // DR-050: BRANCH owns no repository commit — every Coder outcome, including
  // the Boss question for an ambiguous request, is governed with the
  // `unchanged` repository disposition, because a new branch at the current
  // commit changes neither HEAD's OID nor the worktree projection.
  outcomeAuthority: {
    governedPlayerStates: {
      createBranch: {
        branched: {
          fields: {
            branch: 'semantic',
            // DR-045: the unchanged receipt observes the commit the branch
            // was created from as HEAD; the reconciler injects it here.
            baseRevision: 'effect',
            issueSummary: 'semantic',
          },
          repositoryDisposition: 'unchanged',
        },
        refused: {
          fields: { coderOutput: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
      },
    },
  },
  composePlayerPrompt: (input: PlaybookPlayerInput, _identity, resuming) =>
    composePlayerPrompt(input as PlayerInput, resuming),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  controlContextFields: [],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: ['callerInput', 'answer', 'questionId'],
} satisfies XStatePlaybookRuntimeSpecV3<BranchPlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    BranchPlaybookOptions,
    BranchPlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  BranchPlaybookOptions,
  BranchPlaybookHostCapabilities
>(branchMachine, runtimeSpec);

export default createPlaybookRuntime;
