// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./review.fsm.ts
// Role metadata: Coder→coder, Reviewer→reviewer (canonical local roles)
// Boss event:    deterministic START_REVIEW entry; exact Boss text becomes
//                callerInput; pending player questions retain BOSS_REPLY
// Adjudication:  LLM judge per state; coderOutput and reviewerOutput are
//                carried verbatim
// Compat:        artifact schema 2 / runtime ABI 1

import {
  RUNTIME_ABI,
  createXStatePlaybookRuntime,
  snapshotJsonValue,
  type PlaybookPlayerInput,
  type XStatePromptIdentity,
  type XStatePlaybookRuntimeSpec,
} from '@sublang/playbook/xstate-runtime';
import {
  reviewMachine,
  type PlayerInput,
  type ReviewInput,
} from './review.fsm.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

export type ReviewPlaybookOptions = ReviewInput;

const PLACEHOLDER = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g;
const CONTINUATION_PREAMBLE =
  'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.';

const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'reviewerOutput',
  'coderOutput',
]);

function snapshotReviewOptions(value: unknown): ReviewPlaybookOptions {
  const captured = snapshotJsonValue(value, 'REVIEW runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('REVIEW runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const key of Object.keys(record)) {
    throw new TypeError(`REVIEW runtime options.${key} is not declared`);
  }
  return captured as unknown as ReviewPlaybookOptions;
}

function placeholderField(token: string): string {
  if (token === '#') return 'irNumber';
  return token.replace(/-([A-Za-z0-9_$])/g, (_match, next: string) =>
    next.toUpperCase(),
  );
}

function quotedContinuation(value: string): string {
  return value.replaceAll('\n', '\n> ');
}

/** Keep every line of a relayed runtime value inside its authored quote. */
function composePlayerPrompt(
  input: PlayerInput,
  promptIdentity: XStatePromptIdentity,
): string {
  const fields = input as unknown as Record<string, unknown>;
  const body = input.prompt.replace(
    PLACEHOLDER,
    (match: string, token: string, offset: number, source: string) => {
      const value =
        token === 'coder-llm'
          ? promptIdentity('coder')
          : token === 'reviewer-llm'
            ? promptIdentity('reviewer')
            : fields[placeholderField(token)];
      if (typeof value !== 'string') return match;
      const lineStart = source.lastIndexOf('\n', offset - 1) + 1;
      return source.slice(lineStart, offset) === '> '
        ? quotedContinuation(value)
        : value;
    },
  );
  if (
    input.pendingBossQuestion === undefined ||
    input.bossReply === undefined
  ) {
    return body;
  }
  return [
    CONTINUATION_PREAMBLE,
    `Boss question:\n${input.pendingBossQuestion.question}`,
    `Boss reply:\n${input.bossReply}`,
    body,
  ].join('\n\n');
}

export const _internal = {
  composePlayerPrompt,
  VERBATIM_PAYLOAD_FIELDS,
};

const runtimeSpec = {
  label: 'REVIEW',
  compat: { artifactSchema: 2, runtimeAbi: RUNTIME_ABI },
  snapshotOptions: snapshotReviewOptions,
  entryEvent: { type: 'START_REVIEW', textField: 'callerInput' },
  roleStates: {
    reviewInitial: {
      role: 'reviewer',
      label:
        'REVIEW-1: Reviewer examines the latest commit against the caller input.',
    },
    addressFindings: {
      role: 'coder',
      label: 'REVIEW-2: Coder accepts or rejects every current review finding.',
    },
    reviewAfterCommit: {
      role: 'reviewer',
      label:
        'REVIEW-3: Reviewer examines the new review-fix commit and repository state.',
    },
    reviewAfterRebuttal: {
      role: 'reviewer',
      label:
        'REVIEW-4: Reviewer adjudicates an all-rejected Coder disposition.',
    },
  },
  composePlayerPrompt: (
    input: PlaybookPlayerInput,
    promptIdentity: XStatePromptIdentity,
  ) => composePlayerPrompt(input as PlayerInput, promptIdentity),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  controlContextFields: [],
  transitionEventFields: [
    'callerInput',
    'bossIntent',
    'targetId',
    'answer',
    'questionId',
  ],
} satisfies XStatePlaybookRuntimeSpec<ReviewPlaybookOptions>;

const createPlaybookRuntime: PlaybookRuntimeFactory<ReviewPlaybookOptions> =
  createXStatePlaybookRuntime(reviewMachine, runtimeSpec);

export default createPlaybookRuntime;
