// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from "./.slc-verify/verify.js";
import * as fsm from "./captain.fsm.js";

const PINNED = {
  "initial": "ready",
  "captain": [
    {
      "state": "decide",
      "actor": "captain",
      "sourceItem": "DECIDE-1",
      "player": "",
      "resultKeys": [
        "deliver",
        "dismiss",
        "recover",
        "respond",
        "resume",
        "runtime",
        "start",
        "switch"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "ready",
          "guarded": true
        },
        {
          "index": 1,
          "target": "close",
          "guarded": true
        },
        {
          "index": 2,
          "target": "close",
          "guarded": true
        },
        {
          "index": 3,
          "target": "close",
          "guarded": true
        },
        {
          "index": 4,
          "target": "close",
          "guarded": true
        },
        {
          "index": 5,
          "target": "close",
          "guarded": true
        },
        {
          "index": 6,
          "target": "close",
          "guarded": true
        },
        {
          "index": 7,
          "target": "close",
          "guarded": true
        },
        {
          "index": 8,
          "target": "failed",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    },
    {
      "state": "command",
      "actor": "captain",
      "sourceItem": "COMMAND-1",
      "player": "",
      "resultKeys": [
        "done"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "ready",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    },
    {
      "state": "close",
      "actor": "captain",
      "sourceItem": "CLOSE-1",
      "player": "",
      "resultKeys": [
        "done"
      ],
      "onDone": [
        {
          "index": 0,
          "target": "ready",
          "guarded": false
        }
      ],
      "onError": [
        {
          "index": 0,
          "target": "failed",
          "guarded": false
        }
      ],
      "on": {}
    }
  ],
  "quiescent": [
    {
      "state": "ready",
      "final": false,
      "on": {
        "BOSS_TURN_UNRESOLVED": [
          {
            "index": 0,
            "target": "decide",
            "guarded": false
          }
        ],
        "BOSS_TURN_RESPOND": [
          {
            "index": 0,
            "target": "command",
            "guarded": false
          }
        ],
        "BOSS_TURN_ACTING": [
          {
            "index": 0,
            "target": "close",
            "guarded": false
          }
        ]
      }
    },
    {
      "state": "failed",
      "final": false,
      "on": {
        "BOSS_TURN_UNRESOLVED": [
          {
            "index": 0,
            "target": "decide",
            "guarded": false
          }
        ],
        "BOSS_TURN_RESPOND": [
          {
            "index": 0,
            "target": "command",
            "guarded": false
          }
        ],
        "BOSS_TURN_ACTING": [
          {
            "index": 0,
            "target": "close",
            "guarded": false
          }
        ]
      }
    },
    {
      "state": "shutdown",
      "final": true,
      "on": {}
    }
  ],
  "rootOn": {
    "HOST_TEARDOWN": [
      {
        "index": 0,
        "target": "shutdown",
        "guarded": false
      }
    ]
  },
  "interruptTargets": []
} as const;

describe("captain: FSM introspection", () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
