// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./code.fsm.ts
// Player bind:   Coder→coder, Reviewer→reviewer,
//                Committer→{coder per CODE-15/17, reviewer per CODE-16}
// Boss event:    slash-prefix (LLM-classifier fallback)
// Adjudication:  LLM-judge per state

import { createActor, fromPromise } from 'xstate';
import {
  codingMachine,
  type CaptainInput,
  type CaptainOutput,
  type CodingEvent,
  type CodingInput,
} from './code.fsm.js';

// Public contract — `PlayerResult`, `PlaybookPorts`, `PlaybookRuntime`,
// `CodePlaybookOptions`, and the default `createPlaybookRuntime` factory
// per slc/link.md and DR-004 §10.

export interface PlayerResult {
  status: 'ok' | 'aborted' | 'error';
  finalText?: string;
  error?: string;
}

export interface PlaybookPorts {
  callPlayer(
    playerId: string,
    prompt: string,
    signal: AbortSignal,
  ): Promise<PlayerResult>;
  callJudge(prompt: string, signal: AbortSignal): Promise<string>;
  emitStatus(message: string, data?: unknown): Promise<void>;
  emitTelemetry(event: { topic: string; payload: unknown }): Promise<void>;
}

export interface PlaybookRuntime {
  init(ports: PlaybookPorts): Promise<void>;
  handleBossInput(turn: { text: string; signal: AbortSignal }): Promise<void>;
  dispose(): Promise<void>;
}

export type CodePlaybookOptions = CodingInput;

// Internal capabilities (DR-004 §10). Each ships with its final
// signature; behavior lands in the per-capability task noted by the
// TODO marker.

// Player-prompt composer — DR-004 §6.
// Substitutes the three placeholder tokens in `input.prompt` (literal
// string replace, no escaping) and prepends labelled blocks for any
// populated structured field. The FSM's prompt body is never re-flowed.
function composePlayerPrompt(input: CaptainInput): string {
  const blocks: string[] = [];
  if (input.intent !== undefined) {
    blocks.push(`Boss intent:\n${input.intent}`);
  }
  if (input.reviews !== undefined) {
    blocks.push(`Review items:\n${input.reviews}`);
  }
  if (input.challenges !== undefined) {
    blocks.push(`Rebuttals:\n${input.challenges}`);
  }
  if (input.taskDescription !== undefined) {
    blocks.push(`Task description:\n${input.taskDescription}`);
  }

  let body = input.prompt;
  if (input.irNumber !== undefined) {
    body = body.replaceAll('<#>', input.irNumber);
  }
  if (input.coderPlayer !== undefined) {
    body = body.replaceAll('<coder-llm>', input.coderPlayer);
  }
  if (input.reviewerPlayer !== undefined) {
    body = body.replaceAll('<reviewer-llm>', input.reviewerPlayer);
  }

  blocks.push(body);
  return blocks.join('\n\n');
}

// Player-id resolver — DR-004 §2.
// Non-composite: Coder→'coder', Reviewer→'reviewer'. The composite
// Committer (= Coder | Reviewer per code.gears.md) resolves per
// populated <playerName>Player field on `CaptainInput`: prefer
// `coderPlayer` (CODE-15/17), fall back to `reviewerPlayer` (CODE-16),
// and finally to the alias's first alternative (Coder) when neither
// is set.
function resolvePlayerId(input: CaptainInput): string {
  switch (input.player) {
    case 'Coder':
      return 'coder';
    case 'Reviewer':
      return 'reviewer';
    case 'Committer':
      if (input.coderPlayer !== undefined) return 'coder';
      if (input.reviewerPlayer !== undefined) return 'reviewer';
      return 'coder';
    default: {
      const exhaustive: never = input.player;
      throw new Error(
        `resolvePlayerId: unknown player ${String(exhaustive)}`,
      );
    }
  }
}

// LLM judge — DR-004 §4. Builds a prompt that lists each declared
// outcome verbatim, asks ports.callJudge for a JSON
// `{ guard, …payloadFields }` response, and returns the parsed
// object once the chosen guard is one of the input.result keys.
// Adjudicator failures (malformed JSON, missing/unknown guard) are
// control-plane errors and propagate via throw per slc/link.md.
async function adjudicate(
  input: CaptainInput,
  finalText: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
): Promise<CaptainOutput> {
  const prompt = buildJudgePrompt(input, finalText);
  const raw = await ports.callJudge(prompt, signal);
  const parsed = parseJudgeJson(raw);
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('adjudicate: judge response is not a JSON object');
  }
  const obj = parsed as Record<string, unknown>;
  const guard = obj.guard;
  if (typeof guard !== 'string') {
    throw new Error('adjudicate: judge response missing string "guard" field');
  }
  if (!Object.prototype.hasOwnProperty.call(input.result, guard)) {
    throw new Error(
      `adjudicate: unknown guard "${guard}" — declared guards: ${Object.keys(
        input.result,
      ).join(', ')}`,
    );
  }
  return obj as CaptainOutput;
}

function buildJudgePrompt(input: CaptainInput, finalText: string): string {
  const lines: string[] = [];
  lines.push(`The ${input.player} just produced this output:`);
  lines.push('');
  lines.push('```');
  lines.push(finalText);
  lines.push('```');
  lines.push('');
  lines.push(
    'Pick exactly one outcome by `guard` and return JSON ' +
      '`{ guard, …payloadFields }`. Required payload fields are ' +
      'named in the outcome description.',
  );
  lines.push('');
  for (const [key, description] of Object.entries(input.result)) {
    lines.push(`- \`${key}\` — ${description}`);
  }
  return lines.join('\n');
}

function parseJudgeJson(raw: string): unknown {
  let text = raw.trim();
  const fence = text.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  if (fence) text = fence[1].trim();
  try {
    return JSON.parse(text);
  } catch (e) {
    throw new Error(
      `adjudicate: judge response is not valid JSON: ${(e as Error).message}`,
    );
  }
}

// Boss-event classifier — DR-004 §3.
async function classifyBossText(
  _text: string,
  _ports: PlaybookPorts,
  _signal: AbortSignal,
): Promise<CodingEvent | undefined> {
  throw new Error('classifyBossText: not yet implemented (IR-004 Task 7)');
}

// Captain-actor bridge — DR-004 §7.
function captainBridge(_ports: PlaybookPorts) {
  return fromPromise(async () => {
    throw new Error('captainBridge: not yet implemented (IR-004 Task 8)');
  });
}

// Internal export surface for tests. Not part of the stable public API;
// the leading underscore signals "subject to change." Each member is
// referenced here so `noUnusedLocals` stays clean while later tasks
// wire the factory body to use them.
export const _internal = {
  composePlayerPrompt,
  resolvePlayerId,
  adjudicate,
  classifyBossText,
  captainBridge,
};

export default function createPlaybookRuntime(
  options: CodePlaybookOptions,
): PlaybookRuntime {
  // Drive-to-quiescence loop and lifecycle wiring land in IR-004
  // Tasks 8–10. References below keep noUnusedLocals satisfied on
  // the scaffold.
  void options;
  void codingMachine;
  void createActor;
  return {
    async init(_ports: PlaybookPorts): Promise<void> {
      throw new Error(
        'createPlaybookRuntime.init: not yet implemented (IR-004 Task 9)',
      );
    },
    async handleBossInput(
      _turn: { text: string; signal: AbortSignal },
    ): Promise<void> {
      throw new Error(
        'createPlaybookRuntime.handleBossInput: not yet implemented (IR-004 Task 9)',
      );
    },
    async dispose(): Promise<void> {
      throw new Error(
        'createPlaybookRuntime.dispose: not yet implemented (IR-004 Task 9)',
      );
    },
  };
}
