// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./code.fsm.ts
// Role metadata: Coder→coder (canonical local role)
// Boss event:    deterministic START_CODE entry; exact Boss text becomes
//                callerInput; pending Coder questions retain BOSS_REPLY
// Adjudication:  LLM judge per player state; coderOutput is carried verbatim;
//                the first phase decides among four semantic outcomes
// Nested call:   literal review target through the shared bridge
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  snapshotJsonValue,
  type PlaybookPlayerInput,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeConstruction,
  type XStatePromptIdentity,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import {
  codingMachine,
  type CodingInput,
  type PlayerInput,
} from './code.fsm.js';
import type { PlaybookHostConstructionCapabilities } from './playbook-captain.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

export type CodePlaybookOptions = CodingInput;
export type CodePlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<CodePlaybookOptions, object>['hostCapabilities'];

const OPTION_KEYS = new Set(['runResults']);
const PLACEHOLDER = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g;
const CONTINUATION_PREAMBLE =
  'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.';

const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'coderOutput',
]);
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set([
  'reportedReviewFailure',
]);

function snapshotCodeOptions(value: unknown): CodePlaybookOptions {
  const captured = snapshotJsonValue(value, 'CODE runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('CODE runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const [key, option] of Object.entries(record)) {
    if (!OPTION_KEYS.has(key)) {
      throw new TypeError(`CODE runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string') {
      throw new TypeError(`CODE runtime options.${key} must be a string`);
    }
  }
  return captured as unknown as CodePlaybookOptions;
}

function placeholderField(token: string): string {
  if (token === '#') return 'irNumber';
  return token.replace(/-([A-Za-z0-9_$])/g, (_match, next: string) =>
    next.toUpperCase(),
  );
}

function quoteContinuation(value: string): string {
  return value.replaceAll('\n', '\n> ');
}

/**
 * Preserve authored Markdown quote markers around every line of relayed
 * runtime text. The generic composer preserves the marker itself; CODE's
 * override additionally keeps a multiline value inside that quote.
 */
function composePlayerPrompt(
  input: PlayerInput,
  promptIdentity: XStatePromptIdentity,
): string {
  const fields = input as unknown as Record<string, unknown>;
  const template = input.prompt
    .split('\n')
    .filter(
      (line) => !(line === '> <run-results>' && input.runResults.length === 0),
    )
    .join('\n');
  const body = template.replace(
    PLACEHOLDER,
    (match: string, token: string, offset: number, source: string) => {
      const value =
        token === 'coder-llm'
          ? promptIdentity('coder')
          : fields[placeholderField(token)];
      if (typeof value !== 'string') return match;
      const lineStart = source.lastIndexOf('\n', offset - 1) + 1;
      const literal = source.slice(lineStart, offset);
      return literal === '> ' ? quoteContinuation(value) : value;
    },
  );
  if (
    input.pendingBossQuestion === undefined ||
    input.bossReply === undefined
  ) {
    return body;
  }
  return [
    CONTINUATION_PREAMBLE,
    `Boss question:\n${input.pendingBossQuestion.question}`,
    `Boss reply:\n${input.bossReply}`,
    body,
  ].join('\n\n');
}

export const _internal = {
  composePlayerPrompt,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
};

const runtimeSpec = {
  label: 'CODE',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotCodeOptions,
  entryEvent: {
    type: 'START_CODE',
    textField: 'callerInput',
    // `startCoding` copies the entry text here, so the failure-state retry
    // reads it back from the persisted machine snapshot and survives a
    // continued session (DR-034).
    contextField: 'callerInput',
  },
  roleStates: {
    runFirstPhase: {
      role: 'coder',
      label:
        'Coder is running the first coding phase: a direct implementation, a new intent record, or an existing intent-record task.',
    },
    runIrTask: {
      role: 'coder',
      label: 'Coder is implementing exactly one unfinished intent-record task.',
    },
  },
  outcomeAuthority: {
    governedPlayerStates: {
      runFirstPhase: {
        directCommit: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        irCommit: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
            irNumber: 'semantic',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        moreTasks: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
            irNumber: 'semantic',
            irTask: 'semantic',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        finalTask: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
            irNumber: 'semantic',
            irTask: 'semantic',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'deferred',
        },
      },
      runIrTask: {
        moreTasks: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
            irNumber: 'semantic',
            irTask: 'semantic',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        finalTask: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
            irNumber: 'semantic',
            irTask: 'semantic',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'deferred',
        },
      },
    },
  },
  composePlayerPrompt: (
    input: PlaybookPlayerInput,
    promptIdentity: XStatePromptIdentity,
  ) => composePlayerPrompt(input as PlayerInput, promptIdentity),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  controlContextFields: ['phase'],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: ['callerInput', 'answer', 'questionId'],
} satisfies XStatePlaybookRuntimeSpecV3<CodePlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    CodePlaybookOptions,
    CodePlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  CodePlaybookOptions,
  CodePlaybookHostCapabilities
>(
  codingMachine,
  runtimeSpec,
);

export default createPlaybookRuntime;
