// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/gears2fsm.md from ./code.gears.md.
import { assign, fromPromise, setup } from 'xstate';
const APPENDED_PHASE_PROMPT = [
    'Keep to the original intent and follow what it asks.',
    'Do not re-run tests or builds whose inputs have not changed since any previous reported run.',
    "Make the phase's minimal changes and then one new commit, following @specs/packages/git.md; never amend an existing commit.",
    'Make the commit message explain concisely what changed and why, including relevant verification.',
    'Identify every new commit you make.',
    'Coder is <coder-llm>.',
];
const FIRST_PHASE_PROMPT = [
    '> <caller-input>',
    '> <run-results>',
    '',
    'First determine whether the coding request starts a new coding intent or continues an existing IR with unfinished work.',
    'If the request may continue an existing IR but does not identify it unambiguously, ask Boss before changing files.',
    '',
    'For a new coding intent, assess whether it can be completed well in one commit.',
    'If it can, implement and test it, update the affected specs, and ensure @specs/map.md remains accurate.',
    'If it cannot, decompose it into tasks sized to exactly one commit each, add a new IR under @specs/intents, and do not implement any IR task in this phase.',
    'Plan affected spec updates before, with, or after their corresponding code changes, either as standalone IR tasks or as explicit work within related tasks.',
    '',
    'For an existing IR, read the identified IR and implement exactly its next unfinished task, including corresponding tests or specs if any.',
    'Do not implement a later task in this phase.',
    "Mark the IR's progress and deliverables when relevant.",
    'If the IR will be finished after this phase, double-check that all acceptance criteria are met.',
    '',
    'Consult @specs/map.md for relevant context and @specs/meta.md for spec requirements, if needed.',
    '',
    ...APPENDED_PHASE_PROMPT,
].join('\n');
const IR_TASK_PROMPT = [
    '> <caller-input>',
    '> <ir-number>',
    '> <run-results>',
    '',
    'Read the identified IR and implement exactly its next unfinished task, including corresponding tests or specs if any.',
    'Do not implement a later task in this phase.',
    "Mark the IR's progress and deliverables when relevant.",
    'If the IR will be finished after this phase, double-check that all acceptance criteria are met.',
    '',
    ...APPENDED_PHASE_PROMPT,
].join('\n');
const NEEDS_BOSS_REPLY_RESULT = "The acting agent's prose surfaces a clarifying question for Boss that the agent cannot answer alone. Output shall include `question: <verbatim question text from the acting agent's prose>`.";
const FIRST_PHASE_RESULTS = {
    directCommit: 'Coder completed and committed the direct implementation phase. Output shall include `coderOutput: <verbatim final text>` and `latestCommit: <commit identity>`.',
    irCommit: 'Coder created and committed a new IR without implementing an IR task. Output shall include `coderOutput: <verbatim final text>`, `latestCommit: <commit identity>`, and `irNumber` identifying the created IR.',
    moreTasks: 'Coder continued an existing IR, completed and committed exactly its next unfinished task, and at least one task remains. Output shall include `coderOutput: <verbatim final text>`, `latestCommit: <commit identity>`, `irNumber` identifying the continued IR, and `irTask` naming the implemented task.',
    finalTask: 'Coder continued an existing IR and completed and committed its final task. Output shall include `coderOutput: <verbatim final text>`, `latestCommit: <commit identity>`, `irNumber` identifying the continued IR, and `irTask` naming the implemented task.',
    needsBossReply: NEEDS_BOSS_REPLY_RESULT,
};
const IR_TASK_RESULTS = {
    moreTasks: "Coder completed and committed exactly the IR's next unfinished task and at least one task remains. Output shall include `coderOutput: <verbatim final text>`, `latestCommit: <commit identity>`, `irNumber` identifying the continued IR, and `irTask` naming the implemented task.",
    finalTask: "Coder completed and committed the IR's final task. Output shall include `coderOutput: <verbatim final text>`, `latestCommit: <commit identity>`, `irNumber` identifying the continued IR, and `irTask` naming the implemented task.",
    needsBossReply: NEEDS_BOSS_REPLY_RESULT,
};
const STATE_DESCRIPTIONS = {
    ready: 'Waiting for a coding intent.',
    runFirstPhase: 'Coder is running the first coding phase: a direct implementation, a new intent record, or an existing intent-record task.',
    reviewFirstCommit: 'The REVIEW playbook is checking the direct or new-IR phase commit.',
    runIrTask: 'Coder is implementing exactly one unfinished intent-record task.',
    reviewIrTask: 'The REVIEW playbook is checking the latest task commit.',
    awaitBossReply: 'Waiting for Boss to answer Coder.',
    failed: 'The coding workflow failed and is waiting for a new coding intent.',
    reportedReviewFailure: 'The coding workflow reported a REVIEW failure and the last code-owned commit.',
    done: "The coding workflow completed after every phase's REVIEW passed with no unsettled findings.",
};
function playbookMeta(stateId, role) {
    return {
        playbook: {
            stateId,
            description: STATE_DESCRIPTIONS[stateId],
            ...(role === undefined ? {} : { role }),
        },
    };
}
// DR-048: a final state additionally declares whether its outcome means the
// workflow succeeded or failed, so a caller learns that from the machine
// rather than from CODE's output fields.
function terminalMeta(stateId, terminal) {
    return {
        playbook: {
            stateId,
            description: STATE_DESCRIPTIONS[stateId],
            terminal,
        },
    };
}
function isRecord(value) {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
        return false;
    }
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
}
function isNonEmptyString(value) {
    return typeof value === 'string' && value.trim().length > 0;
}
function playerOutput(event) {
    if (!isRecord(event))
        return undefined;
    return isRecord(event.output) ? event.output : undefined;
}
function outputGuard(event, guard) {
    return playerOutput(event)?.guard === guard;
}
function outputString(event, field) {
    const value = playerOutput(event)?.[field];
    return isNonEmptyString(value) ? value : undefined;
}
function hasCommittedOutput(event) {
    return (outputString(event, 'coderOutput') !== undefined &&
        outputString(event, 'latestCommit') !== undefined);
}
function hasIrTaskOutput(event) {
    return (hasCommittedOutput(event) &&
        outputString(event, 'irNumber') !== undefined &&
        outputString(event, 'irTask') !== undefined);
}
function isDirectCommit({ event }) {
    return (outputGuard(event, 'directCommit') &&
        hasCommittedOutput(event));
}
function isIrCommit({ event }) {
    return (outputGuard(event, 'irCommit') &&
        hasCommittedOutput(event) &&
        outputString(event, 'irNumber') !== undefined);
}
function isMoreTasks({ event }) {
    return (outputGuard(event, 'moreTasks') &&
        hasIrTaskOutput(event));
}
function isFinalTask({ event }) {
    return (outputGuard(event, 'finalTask') &&
        hasIrTaskOutput(event));
}
function needsBossReply({ event }) {
    return (outputGuard(event, 'needsBossReply') &&
        outputString(event, 'question') !== undefined);
}
function reviewOutput(event) {
    return isRecord(event) ? event.output : undefined;
}
function isReviewApprovedValue(value) {
    if (!isRecord(value))
        return false;
    if (Reflect.ownKeys(value).some((key) => typeof key !== 'string' ||
        (key !== 'noUnsettledFindings' && key !== 'evaluatedRevision'))) {
        return false;
    }
    return (value.noUnsettledFindings === true &&
        isNonEmptyString(value.evaluatedRevision));
}
function reviewApprovedFor(phase) {
    return ({ context, event }) => context.phase === phase && isReviewApprovedValue(reviewOutput(event));
}
function isStateValue(value, ancestors = new Set()) {
    if (typeof value === 'string')
        return true;
    if (!isRecord(value) || ancestors.has(value))
        return false;
    const next = new Set(ancestors).add(value);
    return Reflect.ownKeys(value).every((key) => typeof key === 'string' &&
        Object.prototype.propertyIsEnumerable.call(value, key) &&
        isStateValue(value[key], next));
}
function isStringArray(value) {
    return (Array.isArray(value) &&
        Reflect.ownKeys(value).length === value.length + 1 &&
        Reflect.ownKeys(value).every((key) => {
            if (key === 'length')
                return true;
            return (typeof key === 'string' &&
                /^(0|[1-9][0-9]*)$/.test(key) &&
                Number(key) < value.length);
        }) &&
        value.every((entry) => isNonEmptyString(entry)) &&
        new Set(value).size === value.length);
}
function isPlaybookState(value) {
    if (!isRecord(value))
        return false;
    const allowed = new Set([
        'value',
        'activeStateIds',
        'tags',
        'status',
        'quiescent',
        'stateId',
    ]);
    if (Reflect.ownKeys(value).some((key) => typeof key !== 'string' || !allowed.has(key)) ||
        !Object.prototype.hasOwnProperty.call(value, 'value') ||
        !Object.prototype.hasOwnProperty.call(value, 'activeStateIds') ||
        !Object.prototype.hasOwnProperty.call(value, 'tags') ||
        !Object.prototype.hasOwnProperty.call(value, 'status') ||
        !Object.prototype.hasOwnProperty.call(value, 'quiescent')) {
        return false;
    }
    return (isStateValue(value.value) &&
        isStringArray(value.activeStateIds) &&
        isStringArray(value.tags) &&
        (value.status === 'active' ||
            value.status === 'done' ||
            value.status === 'error' ||
            value.status === 'stopped') &&
        typeof value.quiescent === 'boolean' &&
        (!Object.prototype.hasOwnProperty.call(value, 'stateId') ||
            (isNonEmptyString(value.stateId) &&
                value.activeStateIds.length === 1 &&
                value.activeStateIds[0] === value.stateId)));
}
function nestedResultFromError(error) {
    if (!(error instanceof Error))
        return undefined;
    const result = error.result;
    return isRecord(result) ? result : undefined;
}
function isFailureTerminalRecord(value) {
    if (!isRecord(value))
        return false;
    const allowed = new Set(['stateId', 'kind', 'description']);
    return (Reflect.ownKeys(value).every((key) => typeof key === 'string' && allowed.has(key)) &&
        isNonEmptyString(value.stateId) &&
        value.kind === 'failure' &&
        (!Object.prototype.hasOwnProperty.call(value, 'description') ||
            typeof value.description === 'string'));
}
function normalizedReviewFailure(error) {
    const result = nestedResultFromError(error);
    if (result === undefined)
        return undefined;
    const allowed = new Set([
        'status',
        'playbookId',
        'childSessionId',
        'state',
        ...(result.status === 'ok' ? ['output', 'terminal'] : ['error']),
    ]);
    if (Reflect.ownKeys(result).some((key) => typeof key !== 'string' || !allowed.has(key)) ||
        (result.status !== 'aborted' &&
            result.status !== 'error' &&
            result.status !== 'ok') ||
        result.playbookId !== 'review') {
        return undefined;
    }
    if (Object.prototype.hasOwnProperty.call(result, 'childSessionId') &&
        !isNonEmptyString(result.childSessionId)) {
        return undefined;
    }
    if (Object.prototype.hasOwnProperty.call(result, 'state') &&
        !isPlaybookState(result.state)) {
        return undefined;
    }
    if (result.status === 'ok') {
        if (!Object.prototype.hasOwnProperty.call(result, 'terminal') ||
            !isFailureTerminalRecord(result.terminal) ||
            !isNonEmptyString(result.childSessionId)) {
            return undefined;
        }
        return {
            status: 'ok',
            ...(result.output === undefined
                ? {}
                : { output: result.output }),
        };
    }
    let normalizedError;
    if (Object.prototype.hasOwnProperty.call(result, 'error')) {
        if (!isRecord(result.error))
            return undefined;
        const errorKeys = Reflect.ownKeys(result.error);
        if (errorKeys.some((key) => typeof key !== 'string' ||
            (key !== 'name' && key !== 'message' && key !== 'stack')) ||
            !Object.prototype.hasOwnProperty.call(result.error, 'name') ||
            !Object.prototype.hasOwnProperty.call(result.error, 'message') ||
            !isNonEmptyString(result.error.name) ||
            typeof result.error.message !== 'string' ||
            (Object.prototype.hasOwnProperty.call(result.error, 'stack') &&
                typeof result.error.stack !== 'string')) {
            return undefined;
        }
        normalizedError = {
            name: result.error.name,
            message: result.error.message,
        };
    }
    else if (result.status === 'error') {
        return undefined;
    }
    return {
        status: result.status,
        ...(normalizedError === undefined ? {} : { error: normalizedError }),
    };
}
function authoredReviewFailure({ event }) {
    const error = isRecord(event) ? event.error : undefined;
    return normalizedReviewFailure(error) !== undefined;
}
function compactError(value) {
    if (value instanceof Error) {
        return {
            name: value.name || 'Error',
            message: value.message,
        };
    }
    return { name: 'Error', message: String(value) };
}
function authoredReviewError(event) {
    const outer = isRecord(event) ? event.error : undefined;
    const failure = normalizedReviewFailure(outer);
    if (failure !== undefined && failure.status !== 'ok' && failure.error) {
        return failure.error;
    }
    if (failure?.status === 'aborted') {
        return { name: 'AbortError', message: 'REVIEW was aborted.' };
    }
    return compactError(outer);
}
function quoteRelay(label, value) {
    const lines = value.split('\n');
    return [`> ${label}: ${lines[0] ?? ''}`, ...lines.slice(1).map((line) => `> ${line}`)].join('\n');
}
function reviewScopeLine(context) {
    return (`> Review scope: the commit ${context.latestCommit ?? ''} ` +
        'from this coding phase and its resulting repository state.');
}
function newIntentReviewText(context) {
    return [
        quoteRelay('Original intent', context.callerInput ?? ''),
        reviewScopeLine(context),
        quoteRelay('Coder output', context.coderOutput ?? ''),
    ].join('\n');
}
function irTaskReviewText(context) {
    return [
        quoteRelay('Original intent', context.callerInput ?? ''),
        reviewScopeLine(context),
        quoteRelay('Coder output', context.coderOutput ?? ''),
        quoteRelay('Current IR task', context.irTask ?? ''),
    ].join('\n');
}
const machineSetup = setup({
    types: {},
    actors: {
        player: fromPromise(async () => {
            throw new Error('player actor must be provided by the runner');
        }),
        playbook: fromPromise(async () => {
            throw new Error('playbook actor must be provided by the runner');
        }),
    },
    guards: {
        isDirectCommit,
        isIrCommit,
        isMoreTasks,
        isFinalTask,
        needsBossReply,
        reviewApprovedDirect: reviewApprovedFor('direct'),
        reviewApprovedIrCreated: reviewApprovedFor('ir-created'),
        reviewApprovedMoreTasks: reviewApprovedFor('ir-task-more'),
        reviewApprovedFinalTask: reviewApprovedFor('ir-task-final'),
        authoredReviewFailure,
        emptyBossReply: ({ event }) => event.type === 'BOSS_REPLY' && event.answer.trim().length === 0,
        resumesFirstPhase: ({ context, event }) => event.type === 'BOSS_REPLY' &&
            event.answer.trim().length > 0 &&
            context.pendingBossQuestion?.resumeStateId === 'runFirstPhase' &&
            (event.questionId === undefined || event.questionId === 'runFirstPhase'),
        resumesIrTask: ({ context, event }) => event.type === 'BOSS_REPLY' &&
            event.answer.trim().length > 0 &&
            context.pendingBossQuestion?.resumeStateId === 'runIrTask' &&
            (event.questionId === undefined || event.questionId === 'runIrTask'),
    },
    actions: {
        'playbook.acceptedOutcome': (_args, _params) => undefined,
        startCoding: assign(({ context, event }) => {
            if (event.type !== 'START_CODE')
                return {};
            return {
                runResults: context.runResults,
                callerInput: event.callerInput,
                coderOutput: undefined,
                latestCommit: undefined,
                irNumber: undefined,
                irTask: undefined,
                evaluatedRevision: undefined,
                phase: undefined,
                completion: undefined,
                reviewError: undefined,
                lastError: undefined,
                pendingBossQuestion: undefined,
                bossReply: undefined,
            };
        }),
        rememberDirectCommit: assign(({ event }) => ({
            coderOutput: outputString(event, 'coderOutput'),
            latestCommit: outputString(event, 'latestCommit'),
            phase: 'direct',
            pendingBossQuestion: undefined,
            bossReply: undefined,
        })),
        rememberIrCommit: assign(({ event }) => ({
            coderOutput: outputString(event, 'coderOutput'),
            latestCommit: outputString(event, 'latestCommit'),
            irNumber: outputString(event, 'irNumber'),
            irTask: undefined,
            phase: 'ir-created',
            pendingBossQuestion: undefined,
            bossReply: undefined,
        })),
        rememberMoreTasks: assign(({ event }) => ({
            coderOutput: outputString(event, 'coderOutput'),
            latestCommit: outputString(event, 'latestCommit'),
            irNumber: outputString(event, 'irNumber'),
            irTask: outputString(event, 'irTask'),
            phase: 'ir-task-more',
            pendingBossQuestion: undefined,
            bossReply: undefined,
        })),
        rememberFinalTask: assign(({ event }) => ({
            coderOutput: outputString(event, 'coderOutput'),
            latestCommit: outputString(event, 'latestCommit'),
            irNumber: outputString(event, 'irNumber'),
            irTask: outputString(event, 'irTask'),
            phase: 'ir-task-final',
            pendingBossQuestion: undefined,
            bossReply: undefined,
        })),
        rememberPendingQuestion: assign(({ context, event }) => {
            const question = outputString(event, 'question');
            const output = playerOutput(event);
            const stateId = context.irNumber === undefined ? 'runFirstPhase' : 'runIrTask';
            if (question === undefined || output?.guard !== 'needsBossReply') {
                return { lastError: new Error('Coder question output was malformed') };
            }
            return {
                pendingBossQuestion: {
                    questionId: stateId,
                    resumeStateId: stateId,
                    sourceItem: stateId === 'runFirstPhase' ? 'CODE-1' : 'CODE-3',
                    asker: { kind: 'role', roleId: 'coder' },
                    question,
                },
                bossReply: undefined,
            };
        }),
        rememberBossReply: assign(({ event }) => event.type === 'BOSS_REPLY' ? { bossReply: event.answer } : {}),
        rememberEmptyBossReplyError: assign({
            lastError: () => new Error('BOSS_REPLY received an empty answer'),
            pendingBossQuestion: undefined,
            bossReply: undefined,
        }),
        completeSuccessfully: assign(({ event }) => {
            const output = reviewOutput(event);
            const approved = isReviewApprovedValue(output) ? output : undefined;
            return {
                completion: 'complete',
                evaluatedRevision: approved?.evaluatedRevision,
                reviewError: undefined,
            };
        }),
        completeWithReviewFailure: assign(({ event }) => ({
            completion: 'review-failed',
            reviewError: authoredReviewError(event),
        })),
        completeWithInvalidReviewOutput: assign(({ event }) => ({
            completion: 'review-failed',
            reviewError: {
                name: 'ReviewContractError',
                message: `REVIEW returned an invalid approval result: ` +
                    JSON.stringify(reviewOutput(event)),
            },
        })),
        rememberActorError: assign(({ event }) => ({
            lastError: event.error,
        })),
        rememberMalformedPlayerOutput: assign(({ context }) => ({
            lastError: new Error(`Coder result for ${context.irNumber === undefined ? 'CODE-1' : 'CODE-3'} ` +
                'did not match a declared outcome.'),
        })),
    },
});
export const codingMachine = machineSetup.createMachine({
    id: 'code',
    initial: 'ready',
    context: ({ input }) => ({
        runResults: typeof input.runResults === 'string' ? input.runResults : '',
    }),
    output: ({ context }) => {
        const lastCodeCommit = context.latestCommit;
        if (!isNonEmptyString(lastCodeCommit)) {
            throw new Error('CODE reached a final state without a commit identity');
        }
        if (context.completion === 'review-failed') {
            return {
                status: 'review-failed',
                lastCodeCommit,
                error: context.reviewError ?? {
                    name: 'Error',
                    message: 'REVIEW failed without error detail.',
                },
            };
        }
        const finalEvaluatedRevision = context.evaluatedRevision;
        if (!isNonEmptyString(finalEvaluatedRevision)) {
            throw new Error('CODE completed without an evaluated repository revision');
        }
        return {
            status: 'complete',
            lastCodeCommit,
            finalEvaluatedRevision,
            allReviewsPassed: true,
        };
    },
    states: {
        ready: {
            id: 'ready',
            description: STATE_DESCRIPTIONS.ready,
            meta: playbookMeta('ready'),
            tags: ['playbook.parked'],
            on: {
                START_CODE: { target: 'runFirstPhase', actions: 'startCoding' },
            },
        },
        runFirstPhase: {
            id: 'runFirstPhase',
            description: STATE_DESCRIPTIONS.runFirstPhase,
            meta: playbookMeta('runFirstPhase', 'coder'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'player',
                input: ({ context }) => ({
                    stateId: 'runFirstPhase',
                    role: 'coder',
                    sourceItem: 'CODE-1',
                    prompt: FIRST_PHASE_PROMPT,
                    result: FIRST_PHASE_RESULTS,
                    callerInput: context.callerInput ?? '',
                    runResults: context.runResults,
                    ...(context.pendingBossQuestion === undefined
                        ? {}
                        : { pendingBossQuestion: context.pendingBossQuestion }),
                    ...(context.bossReply === undefined
                        ? {}
                        : { bossReply: context.bossReply }),
                }),
                onDone: [
                    {
                        guard: 'isDirectCommit',
                        target: 'reviewFirstCommit',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runFirstPhase',
                                    target: 'reviewFirstCommit',
                                    acceptedOutcome: 'directCommit',
                                },
                            },
                            'rememberDirectCommit',
                        ],
                    },
                    {
                        guard: 'isIrCommit',
                        target: 'reviewFirstCommit',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runFirstPhase',
                                    target: 'reviewFirstCommit',
                                    acceptedOutcome: 'irCommit',
                                },
                            },
                            'rememberIrCommit',
                        ],
                    },
                    {
                        guard: 'isMoreTasks',
                        target: 'reviewIrTask',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runFirstPhase',
                                    target: 'reviewIrTask',
                                    acceptedOutcome: 'moreTasks',
                                },
                            },
                            'rememberMoreTasks',
                        ],
                    },
                    {
                        guard: 'isFinalTask',
                        target: 'reviewIrTask',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runFirstPhase',
                                    target: 'reviewIrTask',
                                    acceptedOutcome: 'finalTask',
                                },
                            },
                            'rememberFinalTask',
                        ],
                    },
                    {
                        guard: 'needsBossReply',
                        target: 'awaitBossReply',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runFirstPhase',
                                    target: 'awaitBossReply',
                                    acceptedOutcome: 'needsBossReply',
                                },
                            },
                            'rememberPendingQuestion',
                        ],
                    },
                    {
                        target: 'failed',
                        actions: 'rememberMalformedPlayerOutput',
                    },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        reviewFirstCommit: {
            id: 'reviewFirstCommit',
            description: STATE_DESCRIPTIONS.reviewFirstCommit,
            meta: playbookMeta('reviewFirstCommit'),
            tags: ['playbook.suspended'],
            invoke: {
                src: 'playbook',
                input: ({ context }) => ({
                    stateId: 'reviewFirstCommit',
                    sourceItem: 'CODE-2',
                    playbookId: 'review',
                    text: newIntentReviewText(context),
                }),
                onDone: [
                    {
                        guard: 'reviewApprovedDirect',
                        target: 'done',
                        actions: 'completeSuccessfully',
                    },
                    {
                        guard: 'reviewApprovedIrCreated',
                        target: 'runIrTask',
                    },
                    {
                        target: 'reportedReviewFailure',
                        actions: 'completeWithInvalidReviewOutput',
                    },
                ],
                onError: [
                    {
                        guard: 'authoredReviewFailure',
                        target: 'reportedReviewFailure',
                        actions: 'completeWithReviewFailure',
                    },
                    { target: 'failed', actions: 'rememberActorError' },
                ],
            },
        },
        runIrTask: {
            id: 'runIrTask',
            description: STATE_DESCRIPTIONS.runIrTask,
            meta: playbookMeta('runIrTask', 'coder'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'player',
                input: ({ context }) => ({
                    stateId: 'runIrTask',
                    role: 'coder',
                    sourceItem: 'CODE-3',
                    prompt: IR_TASK_PROMPT,
                    result: IR_TASK_RESULTS,
                    callerInput: context.callerInput ?? '',
                    runResults: context.runResults,
                    ...(context.irNumber === undefined
                        ? {}
                        : { irNumber: context.irNumber }),
                    ...(context.pendingBossQuestion === undefined
                        ? {}
                        : { pendingBossQuestion: context.pendingBossQuestion }),
                    ...(context.bossReply === undefined
                        ? {}
                        : { bossReply: context.bossReply }),
                }),
                onDone: [
                    {
                        guard: 'isMoreTasks',
                        target: 'reviewIrTask',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runIrTask',
                                    target: 'reviewIrTask',
                                    acceptedOutcome: 'moreTasks',
                                },
                            },
                            'rememberMoreTasks',
                        ],
                    },
                    {
                        guard: 'isFinalTask',
                        target: 'reviewIrTask',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runIrTask',
                                    target: 'reviewIrTask',
                                    acceptedOutcome: 'finalTask',
                                },
                            },
                            'rememberFinalTask',
                        ],
                    },
                    {
                        guard: 'needsBossReply',
                        target: 'awaitBossReply',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'runIrTask',
                                    target: 'awaitBossReply',
                                    acceptedOutcome: 'needsBossReply',
                                },
                            },
                            'rememberPendingQuestion',
                        ],
                    },
                    {
                        target: 'failed',
                        actions: 'rememberMalformedPlayerOutput',
                    },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        reviewIrTask: {
            id: 'reviewIrTask',
            description: STATE_DESCRIPTIONS.reviewIrTask,
            meta: playbookMeta('reviewIrTask'),
            tags: ['playbook.suspended'],
            invoke: {
                src: 'playbook',
                input: ({ context }) => ({
                    stateId: 'reviewIrTask',
                    sourceItem: 'CODE-4',
                    playbookId: 'review',
                    text: irTaskReviewText(context),
                }),
                onDone: [
                    {
                        guard: 'reviewApprovedMoreTasks',
                        target: 'runIrTask',
                    },
                    {
                        guard: 'reviewApprovedFinalTask',
                        target: 'done',
                        actions: 'completeSuccessfully',
                    },
                    {
                        target: 'reportedReviewFailure',
                        actions: 'completeWithInvalidReviewOutput',
                    },
                ],
                onError: [
                    {
                        guard: 'authoredReviewFailure',
                        target: 'reportedReviewFailure',
                        actions: 'completeWithReviewFailure',
                    },
                    { target: 'failed', actions: 'rememberActorError' },
                ],
            },
        },
        awaitBossReply: {
            id: 'awaitBossReply',
            description: STATE_DESCRIPTIONS.awaitBossReply,
            meta: playbookMeta('awaitBossReply'),
            tags: ['playbook.parked'],
            on: {
                BOSS_REPLY: [
                    {
                        guard: 'emptyBossReply',
                        target: '#failed',
                        actions: 'rememberEmptyBossReplyError',
                    },
                    {
                        guard: 'resumesFirstPhase',
                        target: '#runFirstPhase',
                        reenter: true,
                        actions: 'rememberBossReply',
                    },
                    {
                        guard: 'resumesIrTask',
                        target: '#runIrTask',
                        reenter: true,
                        actions: 'rememberBossReply',
                    },
                ],
                START_CODE: { target: 'runFirstPhase', actions: 'startCoding' },
            },
        },
        failed: {
            id: 'failed',
            description: STATE_DESCRIPTIONS.failed,
            meta: playbookMeta('failed'),
            tags: ['playbook.parked'],
            on: {
                START_CODE: { target: 'runFirstPhase', actions: 'startCoding' },
            },
        },
        reportedReviewFailure: {
            id: 'reportedReviewFailure',
            description: STATE_DESCRIPTIONS.reportedReviewFailure,
            meta: terminalMeta('reportedReviewFailure', 'failure'),
            type: 'final',
        },
        done: {
            id: 'done',
            description: STATE_DESCRIPTIONS.done,
            meta: terminalMeta('done', 'success'),
            type: 'final',
        },
    },
});
export default codingMachine;
