// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./dev.fsm.ts
// Role metadata: Analyst→analyst (canonical local role)
// Boss event:    deterministic START_DEV entry; exact Boss text becomes
//                developmentRequest; pending Analyst questions retain
//                BOSS_REPLY
// Adjudication:  LLM judge for the one Analyst state; planningResult is
//                carried verbatim
// Nested calls:  literal code and decide targets through the shared bridge
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  snapshotJsonValue,
  type PlaybookPlayerInput,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import {
  devMachine,
  type DevInput,
  type PlayerInput,
} from './dev.fsm.js';
import type { PlaybookHostConstructionCapabilities } from '../code.playbook/playbook-captain.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

export type DevPlaybookOptions = DevInput;
export type DevPlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<DevPlaybookOptions, object>['hostCapabilities'];

const OPTION_KEYS = new Set(['runResults']);
const PLACEHOLDER = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g;
const CONTINUATION_PREAMBLE =
  'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.';

const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'planningResult',
]);
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set([
  'reportedChildFailure',
]);

function snapshotDevOptions(value: unknown): DevPlaybookOptions {
  const captured = snapshotJsonValue(value, 'DEV runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('DEV runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const [key, option] of Object.entries(record)) {
    if (!OPTION_KEYS.has(key)) {
      throw new TypeError(`DEV runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string') {
      throw new TypeError(`DEV runtime options.${key} must be a string`);
    }
  }
  return captured as unknown as DevPlaybookOptions;
}

function placeholderField(token: string): string {
  if (token === '#') return 'irNumber';
  return token.replace(/-([A-Za-z0-9_$])/g, (_match, next: string) =>
    next.toUpperCase(),
  );
}

function quotedContinuation(value: string): string {
  return value.replaceAll('\n', '\n> ');
}

/**
 * Preserve authored Markdown quote markers around every line of relayed
 * runtime text. The generic composer preserves the marker itself; DEV's
 * override additionally keeps a multiline value inside that quote and drops
 * the optional relays that have no value yet.
 */
function composePlayerPrompt(input: PlayerInput): string {
  const fields = input as unknown as Record<string, unknown>;
  const template = input.prompt
    .split('\n')
    .filter(
      (line) =>
        !(
          line === '> <discussion-context>' &&
          input.discussionContext.length === 0
        ) &&
        !(line === '> <run-results>' && input.runResults.length === 0),
    )
    .join('\n');
  const body = template.replace(
    PLACEHOLDER,
    (match: string, token: string, offset: number, source: string) => {
      const value = fields[placeholderField(token)];
      if (typeof value !== 'string') return match;
      const lineStart = source.lastIndexOf('\n', offset - 1) + 1;
      const literal = source.slice(lineStart, offset);
      return literal === '> ' ? quotedContinuation(value) : value;
    },
  );
  if (
    input.pendingBossQuestion === undefined ||
    input.bossReply === undefined
  ) {
    return body;
  }
  return [
    CONTINUATION_PREAMBLE,
    `Boss question:\n${input.pendingBossQuestion.question}`,
    `Boss reply:\n${input.bossReply}`,
    body,
  ].join('\n\n');
}

export const _internal = {
  composePlayerPrompt,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
};

const runtimeSpec = {
  label: 'DEV',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotDevOptions,
  entryEvent: {
    type: 'START_DEV',
    textField: 'developmentRequest',
    // `startDev` copies the entry text here, so the failure-state retry
    // reads it back from the persisted machine snapshot and survives a
    // continued session (DR-034).
    contextField: 'developmentRequest',
  },
  roleStates: {
    planAnalysis: {
      role: 'analyst',
      label:
        'Analyst is analyzing the development request to choose the smallest sound next step.',
    },
  },
  // DR-044: DEV owns no repository commit — every Analyst outcome is
  // governed with the `unchanged` repository disposition, so planning that
  // mutates the repository fails authority instead of being adopted.
  outcomeAuthority: {
    governedPlayerStates: {
      planAnalysis: {
        discussionComplete: {
          fields: {},
          repositoryDisposition: 'unchanged',
        },
        code: {
          fields: { planningResult: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
        decideThenCode: {
          fields: { planningResult: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
      },
    },
  },
  composePlayerPrompt: (input: PlaybookPlayerInput) =>
    composePlayerPrompt(input as PlayerInput),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  controlContextFields: [],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: ['developmentRequest', 'answer', 'questionId'],
} satisfies XStatePlaybookRuntimeSpecV3<DevPlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    DevPlaybookOptions,
    DevPlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  DevPlaybookOptions,
  DevPlaybookHostCapabilities
>(devMachine, runtimeSpec);

export default createPlaybookRuntime;
